/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyect_y;

/**
 *
 * @author Kevin G
 */
public class Busqueda1 extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Principal
     */
    public Busqueda1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        InicioBtn = new javax.swing.JButton();
        ExplorarBtn = new javax.swing.JButton();
        ComunidadesBtn = new javax.swing.JButton();
        NotificacionesBtn = new javax.swing.JButton();
        GuardadoBtn = new javax.swing.JButton();
        PerfilBtn = new javax.swing.JButton();
        PostearBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        PerfilPanel = new javax.swing.JPanel();
        Perfil_Img = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        CuentaBtn = new javax.swing.JButton();
        PerfilBtn1 = new javax.swing.JButton();
        PerfilBtn2 = new javax.swing.JButton();
        PerfilBtn3 = new javax.swing.JButton();
        PerfilBtn4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        CuentaBtn1 = new javax.swing.JButton();
        CuentaBtn7 = new javax.swing.JButton();
        IdUsuario = new javax.swing.JLabel();
        NombreUsuario = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        CuentaBtn13 = new javax.swing.JButton();
        CuentaBtn14 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        CuentaBtn15 = new javax.swing.JButton();
        CuentaBtn16 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        CuentaBtn17 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel40 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        CuentaBtn6 = new javax.swing.JButton();
        CuentaBtn18 = new javax.swing.JButton();
        CuentaBtn19 = new javax.swing.JButton();
        CuentaBtn20 = new javax.swing.JButton();
        CuentaBtn22 = new javax.swing.JButton();
        CuentaBtn23 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        CuentaBtn24 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        SeguridadYAccesoBtn4 = new javax.swing.JButton();
        SeguridadYAccesoBtn5 = new javax.swing.JButton();
        SeguridadYAccesoBtn6 = new javax.swing.JButton();
        SeguridadYAccesoBtn8 = new javax.swing.JButton();
        SeguridadYAccesoBtn = new javax.swing.JButton();
        SeguridadYAccesoBtn7 = new javax.swing.JButton();
        SeguridadYAccesoBtn9 = new javax.swing.JButton();
        SeguridadYAccesoBtn10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        SeguridadYAccesoBtn3 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        CuentaBtn10 = new javax.swing.JButton();
        CuentaBtn11 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        SeguridadYAccesoBtn11 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        CuentaBtn2 = new javax.swing.JButton();
        CuentaBtn5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        SeguridadYAccesoBtn12 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        CuentaBtn4 = new javax.swing.JButton();
        CuentaBtn12 = new javax.swing.JButton();
        PostearBtn1 = new javax.swing.JButton();
        PostearBtn2 = new javax.swing.JButton();
        PostearBtn3 = new javax.swing.JButton();
        PostearBtn4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InicioBtn.setBackground(new java.awt.Color(26, 26, 29));
        InicioBtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        InicioBtn.setForeground(new java.awt.Color(204, 204, 204));
        InicioBtn.setText("  🏚Inicio");
        InicioBtn.setToolTipText("");
        InicioBtn.setAlignmentY(0.0F);
        InicioBtn.setBorderPainted(false);
        InicioBtn.setContentAreaFilled(false);
        InicioBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        InicioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioBtnActionPerformed(evt);
            }
        });
        jPanel1.add(InicioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 200, 40));

        ExplorarBtn.setBackground(new java.awt.Color(26, 26, 29));
        ExplorarBtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        ExplorarBtn.setForeground(new java.awt.Color(204, 204, 204));
        ExplorarBtn.setText("  🔍Explorar");
        ExplorarBtn.setToolTipText("");
        ExplorarBtn.setAlignmentY(0.0F);
        ExplorarBtn.setBorderPainted(false);
        ExplorarBtn.setContentAreaFilled(false);
        ExplorarBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ExplorarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExplorarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ExplorarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 200, 40));

        ComunidadesBtn.setBackground(new java.awt.Color(26, 26, 29));
        ComunidadesBtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        ComunidadesBtn.setForeground(new java.awt.Color(204, 204, 204));
        ComunidadesBtn.setText("  Mensajes");
        ComunidadesBtn.setToolTipText("");
        ComunidadesBtn.setAlignmentY(0.0F);
        ComunidadesBtn.setBorderPainted(false);
        ComunidadesBtn.setContentAreaFilled(false);
        ComunidadesBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ComunidadesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComunidadesBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ComunidadesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 200, 40));

        NotificacionesBtn.setBackground(new java.awt.Color(26, 26, 29));
        NotificacionesBtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        NotificacionesBtn.setForeground(new java.awt.Color(204, 204, 204));
        NotificacionesBtn.setText("  Notificaciones");
        NotificacionesBtn.setToolTipText("");
        NotificacionesBtn.setAlignmentY(0.0F);
        NotificacionesBtn.setBorderPainted(false);
        NotificacionesBtn.setContentAreaFilled(false);
        NotificacionesBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        NotificacionesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotificacionesBtnActionPerformed(evt);
            }
        });
        jPanel1.add(NotificacionesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 200, 40));

        GuardadoBtn.setBackground(new java.awt.Color(26, 26, 29));
        GuardadoBtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        GuardadoBtn.setForeground(new java.awt.Color(204, 204, 204));
        GuardadoBtn.setText("  Listas");
        GuardadoBtn.setToolTipText("");
        GuardadoBtn.setAlignmentY(0.0F);
        GuardadoBtn.setBorderPainted(false);
        GuardadoBtn.setContentAreaFilled(false);
        GuardadoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        GuardadoBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        GuardadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardadoBtnActionPerformed(evt);
            }
        });
        jPanel1.add(GuardadoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 200, 40));

        PerfilBtn.setBackground(new java.awt.Color(26, 26, 29));
        PerfilBtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        PerfilBtn.setForeground(new java.awt.Color(204, 204, 204));
        PerfilBtn.setText("  Mas");
        PerfilBtn.setToolTipText("");
        PerfilBtn.setAlignmentY(0.0F);
        PerfilBtn.setBorderPainted(false);
        PerfilBtn.setContentAreaFilled(false);
        PerfilBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PerfilBtn.setVerifyInputWhenFocusTarget(false);
        PerfilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilBtnActionPerformed(evt);
            }
        });
        jPanel1.add(PerfilBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, 200, 40));

        PostearBtn.setBackground(new java.awt.Color(166, 77, 121));
        PostearBtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        PostearBtn.setForeground(new java.awt.Color(204, 204, 204));
        PostearBtn.setText("Menciones de ti");
        PostearBtn.setToolTipText("");
        PostearBtn.setAlignmentY(0.0F);
        PostearBtn.setBorderPainted(false);
        PostearBtn.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        PostearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostearBtnActionPerformed(evt);
            }
        });
        jPanel1.add(PostearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 660, 210, 50));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 0, -1, 1040));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 570, 490, -1));

        PerfilPanel.setBackground(new java.awt.Color(0, 0, 0));
        PerfilPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PerfilPanel.add(Perfil_Img, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 40));

        jPanel1.add(PerfilPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 720, 270, 60));

        jSeparator4.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator4.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 10, 1040));

        CuentaBtn.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        CuentaBtn.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn.setText("1000 publicaciones");
        CuentaBtn.setBorder(null);
        CuentaBtn.setBorderPainted(false);
        CuentaBtn.setContentAreaFilled(false);
        CuentaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 490, 100, 30));

        PerfilBtn1.setBackground(new java.awt.Color(26, 26, 29));
        PerfilBtn1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        PerfilBtn1.setForeground(new java.awt.Color(204, 204, 204));
        PerfilBtn1.setText("  Marcadores");
        PerfilBtn1.setToolTipText("");
        PerfilBtn1.setAlignmentY(0.0F);
        PerfilBtn1.setBorderPainted(false);
        PerfilBtn1.setContentAreaFilled(false);
        PerfilBtn1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PerfilBtn1.setVerifyInputWhenFocusTarget(false);
        PerfilBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(PerfilBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 200, 40));

        PerfilBtn2.setBackground(new java.awt.Color(26, 26, 29));
        PerfilBtn2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        PerfilBtn2.setForeground(new java.awt.Color(204, 204, 204));
        PerfilBtn2.setText("  Trabajos");
        PerfilBtn2.setToolTipText("");
        PerfilBtn2.setAlignmentY(0.0F);
        PerfilBtn2.setBorderPainted(false);
        PerfilBtn2.setContentAreaFilled(false);
        PerfilBtn2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PerfilBtn2.setVerifyInputWhenFocusTarget(false);
        PerfilBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilBtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(PerfilBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 200, 40));

        PerfilBtn3.setBackground(new java.awt.Color(26, 26, 29));
        PerfilBtn3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        PerfilBtn3.setForeground(new java.awt.Color(204, 204, 204));
        PerfilBtn3.setText("  Comunidad");
        PerfilBtn3.setToolTipText("");
        PerfilBtn3.setAlignmentY(0.0F);
        PerfilBtn3.setBorderPainted(false);
        PerfilBtn3.setContentAreaFilled(false);
        PerfilBtn3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PerfilBtn3.setVerifyInputWhenFocusTarget(false);
        PerfilBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilBtn3ActionPerformed(evt);
            }
        });
        jPanel1.add(PerfilBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 200, 40));

        PerfilBtn4.setBackground(new java.awt.Color(26, 26, 29));
        PerfilBtn4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        PerfilBtn4.setForeground(new java.awt.Color(204, 204, 204));
        PerfilBtn4.setText("  Perfil");
        PerfilBtn4.setToolTipText("");
        PerfilBtn4.setAlignmentY(0.0F);
        PerfilBtn4.setBorderPainted(false);
        PerfilBtn4.setContentAreaFilled(false);
        PerfilBtn4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PerfilBtn4.setVerifyInputWhenFocusTarget(false);
        PerfilBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilBtn4ActionPerformed(evt);
            }
        });
        jPanel1.add(PerfilBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 200, 40));

        jButton2.setBackground(new java.awt.Color(166, 77, 121));
        jButton2.setText("Eliminar busquedas");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 140, 30));

        jLabel38.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(204, 204, 204));
        jLabel38.setText("Qué pasa");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 350, 210, 30));

        CuentaBtn1.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        CuentaBtn1.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn1.setText("Ver todo");
        CuentaBtn1.setBorder(null);
        CuentaBtn1.setBorderPainted(false);
        CuentaBtn1.setContentAreaFilled(false);
        CuentaBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 100, 70, 40));

        CuentaBtn7.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        CuentaBtn7.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn7.setText("00000");
        CuentaBtn7.setBorder(null);
        CuentaBtn7.setBorderPainted(false);
        CuentaBtn7.setContentAreaFilled(false);
        CuentaBtn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn7ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 220, 80, 50));

        IdUsuario.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        IdUsuario.setForeground(new java.awt.Color(106, 30, 85));
        IdUsuario.setText("@Usuario1");
        jPanel1.add(IdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 1000, -1, -1));

        NombreUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        NombreUsuario.setForeground(new java.awt.Color(204, 204, 204));
        NombreUsuario.setText("Usuario Ejemplo");
        jPanel1.add(NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 980, -1, -1));

        jButton1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("...");
        jButton1.setAlignmentY(0.0F);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 460, 50, 40));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("🔍Buscar");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 450, 30));

        jLabel39.setFont(new java.awt.Font("Roboto Black", 1, 22)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(204, 204, 204));
        jLabel39.setText("Usuario");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 100, 30));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("Seguir");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 230, -1, -1));

        CuentaBtn13.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        CuentaBtn13.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn13.setText("''''''''");
        CuentaBtn13.setBorder(null);
        CuentaBtn13.setBorderPainted(false);
        CuentaBtn13.setContentAreaFilled(false);
        CuentaBtn13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn13ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 110, 80, 50));

        CuentaBtn14.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        CuentaBtn14.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn14.setText("00000");
        CuentaBtn14.setBorder(null);
        CuentaBtn14.setBorderPainted(false);
        CuentaBtn14.setContentAreaFilled(false);
        CuentaBtn14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn14ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 120, 80, 50));

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setText("Seguir");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 130, -1, -1));

        CuentaBtn15.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        CuentaBtn15.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn15.setText("''''''''");
        CuentaBtn15.setBorder(null);
        CuentaBtn15.setBorderPainted(false);
        CuentaBtn15.setContentAreaFilled(false);
        CuentaBtn15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn15ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 160, 80, 50));

        CuentaBtn16.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        CuentaBtn16.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn16.setText("00000");
        CuentaBtn16.setBorder(null);
        CuentaBtn16.setBorderPainted(false);
        CuentaBtn16.setContentAreaFilled(false);
        CuentaBtn16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn16ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 170, 80, 50));

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setText("Seguir");
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 180, -1, -1));

        CuentaBtn17.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        CuentaBtn17.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn17.setText("''''''''");
        CuentaBtn17.setBorder(null);
        CuentaBtn17.setBorderPainted(false);
        CuentaBtn17.setContentAreaFilled(false);
        CuentaBtn17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn17ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 210, 80, 50));

        jSeparator5.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator5.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 10, 1040));

        jSeparator6.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator6.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 80, 80, 220));

        jSeparator7.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator7.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 80, 20, 220));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 300, 280, 20));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 80, 280, 10));

        jLabel40.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(204, 204, 204));
        jLabel40.setText("Te puede interesar");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 80, 210, 30));

        jButton4.setBackground(new java.awt.Color(106, 30, 85));
        jButton4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(106, 30, 85));
        jButton4.setText("...");
        jButton4.setAlignmentY(0.0F);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 980, 50, 40));

        CuentaBtn6.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        CuentaBtn6.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn6.setText("Tendencia");
        CuentaBtn6.setBorder(null);
        CuentaBtn6.setBorderPainted(false);
        CuentaBtn6.setContentAreaFilled(false);
        CuentaBtn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn6ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 450, 80, 30));

        CuentaBtn18.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        CuentaBtn18.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn18.setText("#0000");
        CuentaBtn18.setBorder(null);
        CuentaBtn18.setBorderPainted(false);
        CuentaBtn18.setContentAreaFilled(false);
        CuentaBtn18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn18ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn18, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 460, 80, 50));

        CuentaBtn19.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        CuentaBtn19.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn19.setText("Mostrar mas");
        CuentaBtn19.setBorder(null);
        CuentaBtn19.setBorderPainted(false);
        CuentaBtn19.setContentAreaFilled(false);
        CuentaBtn19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn19ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn19, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 510, 80, 50));

        CuentaBtn20.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        CuentaBtn20.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn20.setText("Tendencia");
        CuentaBtn20.setBorder(null);
        CuentaBtn20.setBorderPainted(false);
        CuentaBtn20.setContentAreaFilled(false);
        CuentaBtn20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn20ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn20, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 380, 80, 30));

        CuentaBtn22.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        CuentaBtn22.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn22.setText("#0000");
        CuentaBtn22.setBorder(null);
        CuentaBtn22.setBorderPainted(false);
        CuentaBtn22.setContentAreaFilled(false);
        CuentaBtn22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn22ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn22, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 390, 80, 50));

        CuentaBtn23.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        CuentaBtn23.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn23.setText("1000 publicaciones");
        CuentaBtn23.setBorder(null);
        CuentaBtn23.setBorderPainted(false);
        CuentaBtn23.setContentAreaFilled(false);
        CuentaBtn23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn23ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn23, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 410, 100, 50));

        jButton8.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("...");
        jButton8.setAlignmentY(0.0F);
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 380, 50, 40));

        CuentaBtn24.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        CuentaBtn24.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn24.setText("Mostrar mas");
        CuentaBtn24.setBorder(null);
        CuentaBtn24.setBorderPainted(false);
        CuentaBtn24.setContentAreaFilled(false);
        CuentaBtn24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn24ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 260, 80, 50));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        SeguridadYAccesoBtn4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        SeguridadYAccesoBtn4.setForeground(new java.awt.Color(204, 204, 204));
        SeguridadYAccesoBtn4.setText("Personas");
        SeguridadYAccesoBtn4.setToolTipText("");
        SeguridadYAccesoBtn4.setBorder(null);
        SeguridadYAccesoBtn4.setBorderPainted(false);
        SeguridadYAccesoBtn4.setContentAreaFilled(false);
        SeguridadYAccesoBtn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SeguridadYAccesoBtn4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeguridadYAccesoBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguridadYAccesoBtn4ActionPerformed(evt);
            }
        });

        SeguridadYAccesoBtn5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        SeguridadYAccesoBtn5.setForeground(new java.awt.Color(204, 204, 204));
        SeguridadYAccesoBtn5.setText("Comunidades");
        SeguridadYAccesoBtn5.setToolTipText("");
        SeguridadYAccesoBtn5.setBorder(null);
        SeguridadYAccesoBtn5.setBorderPainted(false);
        SeguridadYAccesoBtn5.setContentAreaFilled(false);
        SeguridadYAccesoBtn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SeguridadYAccesoBtn5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeguridadYAccesoBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguridadYAccesoBtn5ActionPerformed(evt);
            }
        });

        SeguridadYAccesoBtn6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        SeguridadYAccesoBtn6.setForeground(new java.awt.Color(204, 204, 204));
        SeguridadYAccesoBtn6.setText("Yap's");
        SeguridadYAccesoBtn6.setToolTipText("");
        SeguridadYAccesoBtn6.setBorder(null);
        SeguridadYAccesoBtn6.setBorderPainted(false);
        SeguridadYAccesoBtn6.setContentAreaFilled(false);
        SeguridadYAccesoBtn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SeguridadYAccesoBtn6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeguridadYAccesoBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguridadYAccesoBtn6ActionPerformed(evt);
            }
        });

        SeguridadYAccesoBtn8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        SeguridadYAccesoBtn8.setForeground(new java.awt.Color(204, 204, 204));
        SeguridadYAccesoBtn8.setToolTipText("");
        SeguridadYAccesoBtn8.setBorder(null);
        SeguridadYAccesoBtn8.setBorderPainted(false);
        SeguridadYAccesoBtn8.setContentAreaFilled(false);
        SeguridadYAccesoBtn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SeguridadYAccesoBtn8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeguridadYAccesoBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguridadYAccesoBtn8ActionPerformed(evt);
            }
        });

        SeguridadYAccesoBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        SeguridadYAccesoBtn.setForeground(new java.awt.Color(204, 204, 204));
        SeguridadYAccesoBtn.setText("Le gusta");
        SeguridadYAccesoBtn.setToolTipText("");
        SeguridadYAccesoBtn.setBorder(null);
        SeguridadYAccesoBtn.setBorderPainted(false);
        SeguridadYAccesoBtn.setContentAreaFilled(false);
        SeguridadYAccesoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SeguridadYAccesoBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeguridadYAccesoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguridadYAccesoBtnActionPerformed(evt);
            }
        });

        SeguridadYAccesoBtn7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        SeguridadYAccesoBtn7.setForeground(new java.awt.Color(204, 204, 204));
        SeguridadYAccesoBtn7.setText("Todo");
        SeguridadYAccesoBtn7.setToolTipText("");
        SeguridadYAccesoBtn7.setBorder(null);
        SeguridadYAccesoBtn7.setBorderPainted(false);
        SeguridadYAccesoBtn7.setContentAreaFilled(false);
        SeguridadYAccesoBtn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SeguridadYAccesoBtn7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeguridadYAccesoBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguridadYAccesoBtn7ActionPerformed(evt);
            }
        });

        SeguridadYAccesoBtn9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        SeguridadYAccesoBtn9.setForeground(new java.awt.Color(204, 204, 204));
        SeguridadYAccesoBtn9.setText("Eventos");
        SeguridadYAccesoBtn9.setToolTipText("");
        SeguridadYAccesoBtn9.setBorder(null);
        SeguridadYAccesoBtn9.setBorderPainted(false);
        SeguridadYAccesoBtn9.setContentAreaFilled(false);
        SeguridadYAccesoBtn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SeguridadYAccesoBtn9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeguridadYAccesoBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguridadYAccesoBtn9ActionPerformed(evt);
            }
        });

        SeguridadYAccesoBtn10.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        SeguridadYAccesoBtn10.setForeground(new java.awt.Color(204, 204, 204));
        SeguridadYAccesoBtn10.setText("Multimedia");
        SeguridadYAccesoBtn10.setToolTipText("");
        SeguridadYAccesoBtn10.setBorder(null);
        SeguridadYAccesoBtn10.setBorderPainted(false);
        SeguridadYAccesoBtn10.setContentAreaFilled(false);
        SeguridadYAccesoBtn10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SeguridadYAccesoBtn10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeguridadYAccesoBtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguridadYAccesoBtn10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SeguridadYAccesoBtn7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SeguridadYAccesoBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SeguridadYAccesoBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SeguridadYAccesoBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SeguridadYAccesoBtn9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SeguridadYAccesoBtn10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeguridadYAccesoBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(SeguridadYAccesoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SeguridadYAccesoBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeguridadYAccesoBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeguridadYAccesoBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeguridadYAccesoBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeguridadYAccesoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeguridadYAccesoBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeguridadYAccesoBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeguridadYAccesoBtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 490, 40));

        jPanel3.setBackground(new java.awt.Color(106, 30, 85));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        SeguridadYAccesoBtn3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        SeguridadYAccesoBtn3.setForeground(new java.awt.Color(204, 204, 204));
        SeguridadYAccesoBtn3.setText("@Usuario");
        SeguridadYAccesoBtn3.setToolTipText("");
        SeguridadYAccesoBtn3.setBorder(null);
        SeguridadYAccesoBtn3.setBorderPainted(false);
        SeguridadYAccesoBtn3.setContentAreaFilled(false);
        SeguridadYAccesoBtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SeguridadYAccesoBtn3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeguridadYAccesoBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguridadYAccesoBtn3ActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Roboto Black", 1, 22)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(204, 204, 204));
        jLabel37.setText("Usuario");

        CuentaBtn10.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        CuentaBtn10.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn10.setText("Seguidores");
        CuentaBtn10.setBorder(null);
        CuentaBtn10.setBorderPainted(false);
        CuentaBtn10.setContentAreaFilled(false);
        CuentaBtn10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn10ActionPerformed(evt);
            }
        });

        CuentaBtn11.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        CuentaBtn11.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn11.setText("0");
        CuentaBtn11.setBorder(null);
        CuentaBtn11.setBorderPainted(false);
        CuentaBtn11.setContentAreaFilled(false);
        CuentaBtn11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SeguridadYAccesoBtn3)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addComponent(CuentaBtn11, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CuentaBtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeguridadYAccesoBtn3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CuentaBtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CuentaBtn11))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 470, 70));

        jPanel4.setBackground(new java.awt.Color(59, 28, 50));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        SeguridadYAccesoBtn11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        SeguridadYAccesoBtn11.setForeground(new java.awt.Color(204, 204, 204));
        SeguridadYAccesoBtn11.setText("@Usuario");
        SeguridadYAccesoBtn11.setToolTipText("");
        SeguridadYAccesoBtn11.setBorder(null);
        SeguridadYAccesoBtn11.setBorderPainted(false);
        SeguridadYAccesoBtn11.setContentAreaFilled(false);
        SeguridadYAccesoBtn11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SeguridadYAccesoBtn11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeguridadYAccesoBtn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguridadYAccesoBtn11ActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Roboto Black", 1, 22)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(204, 204, 204));
        jLabel41.setText("Usuario");

        CuentaBtn2.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        CuentaBtn2.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn2.setText("Seguidores");
        CuentaBtn2.setBorder(null);
        CuentaBtn2.setBorderPainted(false);
        CuentaBtn2.setContentAreaFilled(false);
        CuentaBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn2ActionPerformed(evt);
            }
        });

        CuentaBtn5.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        CuentaBtn5.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn5.setText("0");
        CuentaBtn5.setBorder(null);
        CuentaBtn5.setBorderPainted(false);
        CuentaBtn5.setContentAreaFilled(false);
        CuentaBtn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SeguridadYAccesoBtn11)
                    .addComponent(jLabel41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addComponent(CuentaBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CuentaBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeguridadYAccesoBtn11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CuentaBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CuentaBtn5))
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 470, 70));

        jPanel5.setBackground(new java.awt.Color(166, 77, 121));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        SeguridadYAccesoBtn12.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        SeguridadYAccesoBtn12.setForeground(new java.awt.Color(204, 204, 204));
        SeguridadYAccesoBtn12.setText("@Usuario");
        SeguridadYAccesoBtn12.setToolTipText("");
        SeguridadYAccesoBtn12.setBorder(null);
        SeguridadYAccesoBtn12.setBorderPainted(false);
        SeguridadYAccesoBtn12.setContentAreaFilled(false);
        SeguridadYAccesoBtn12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SeguridadYAccesoBtn12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeguridadYAccesoBtn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguridadYAccesoBtn12ActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Roboto Black", 1, 22)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(204, 204, 204));
        jLabel42.setText("Usuario");

        CuentaBtn4.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        CuentaBtn4.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn4.setText("Seguidores");
        CuentaBtn4.setBorder(null);
        CuentaBtn4.setBorderPainted(false);
        CuentaBtn4.setContentAreaFilled(false);
        CuentaBtn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn4ActionPerformed(evt);
            }
        });

        CuentaBtn12.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        CuentaBtn12.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn12.setText("0");
        CuentaBtn12.setBorder(null);
        CuentaBtn12.setBorderPainted(false);
        CuentaBtn12.setContentAreaFilled(false);
        CuentaBtn12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SeguridadYAccesoBtn12)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addComponent(CuentaBtn12, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CuentaBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeguridadYAccesoBtn12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CuentaBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CuentaBtn12))
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, -1, -1));

        PostearBtn1.setBackground(new java.awt.Color(166, 77, 121));
        PostearBtn1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        PostearBtn1.setForeground(new java.awt.Color(204, 204, 204));
        PostearBtn1.setText(" Exponer");
        PostearBtn1.setToolTipText("");
        PostearBtn1.setAlignmentY(0.0F);
        PostearBtn1.setBorderPainted(false);
        PostearBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostearBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(PostearBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 920, 200, 40));

        PostearBtn2.setBackground(new java.awt.Color(106, 30, 85));
        PostearBtn2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        PostearBtn2.setForeground(new java.awt.Color(204, 204, 204));
        PostearBtn2.setText(" Cumpleaños");
        PostearBtn2.setToolTipText("");
        PostearBtn2.setAlignmentY(0.0F);
        PostearBtn2.setBorderPainted(false);
        PostearBtn2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        PostearBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostearBtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(PostearBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 660, 210, 50));

        PostearBtn3.setBackground(new java.awt.Color(106, 30, 85));
        PostearBtn3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        PostearBtn3.setForeground(new java.awt.Color(204, 204, 204));
        PostearBtn3.setText("Tus Yap's");
        PostearBtn3.setToolTipText("");
        PostearBtn3.setAlignmentY(0.0F);
        PostearBtn3.setBorderPainted(false);
        PostearBtn3.setHideActionText(true);
        PostearBtn3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        PostearBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostearBtn3ActionPerformed(evt);
            }
        });
        jPanel1.add(PostearBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, 210, 50));

        PostearBtn4.setBackground(new java.awt.Color(166, 77, 121));
        PostearBtn4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        PostearBtn4.setForeground(new java.awt.Color(204, 204, 204));
        PostearBtn4.setText("Amigos");
        PostearBtn4.setToolTipText("");
        PostearBtn4.setAlignmentY(0.0F);
        PostearBtn4.setBorderPainted(false);
        PostearBtn4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        PostearBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostearBtn4ActionPerformed(evt);
            }
        });
        jPanel1.add(PostearBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 590, 210, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1042, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InicioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InicioBtnActionPerformed

    private void ComunidadesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComunidadesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComunidadesBtnActionPerformed

    private void NotificacionesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotificacionesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NotificacionesBtnActionPerformed

    private void GuardadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardadoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardadoBtnActionPerformed

    private void PerfilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerfilBtnActionPerformed

    private void PostearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostearBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PostearBtnActionPerformed

    private void CuentaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtnActionPerformed
        
    }//GEN-LAST:event_CuentaBtnActionPerformed

    private void SeguridadYAccesoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguridadYAccesoBtnActionPerformed

    }//GEN-LAST:event_SeguridadYAccesoBtnActionPerformed

    private void ExplorarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExplorarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExplorarBtnActionPerformed

    private void PerfilBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerfilBtn1ActionPerformed

    private void PerfilBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerfilBtn2ActionPerformed

    private void PerfilBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerfilBtn3ActionPerformed

    private void PerfilBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerfilBtn4ActionPerformed

    private void CuentaBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn1ActionPerformed

    private void CuentaBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn5ActionPerformed

    private void CuentaBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn7ActionPerformed

    private void SeguridadYAccesoBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguridadYAccesoBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeguridadYAccesoBtn3ActionPerformed

    private void SeguridadYAccesoBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguridadYAccesoBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeguridadYAccesoBtn4ActionPerformed

    private void SeguridadYAccesoBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguridadYAccesoBtn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeguridadYAccesoBtn5ActionPerformed

    private void SeguridadYAccesoBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguridadYAccesoBtn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeguridadYAccesoBtn6ActionPerformed

    private void SeguridadYAccesoBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguridadYAccesoBtn7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeguridadYAccesoBtn7ActionPerformed

    private void SeguridadYAccesoBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguridadYAccesoBtn8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeguridadYAccesoBtn8ActionPerformed

    private void CuentaBtn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn13ActionPerformed

    private void CuentaBtn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn14ActionPerformed

    private void CuentaBtn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn15ActionPerformed

    private void CuentaBtn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn16ActionPerformed

    private void CuentaBtn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn17ActionPerformed

    private void CuentaBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn2ActionPerformed

    private void CuentaBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn6ActionPerformed
        // TODO add your handling code here:coment
        //ola
    }//GEN-LAST:event_CuentaBtn6ActionPerformed

    private void CuentaBtn18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn18ActionPerformed

    private void CuentaBtn19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn19ActionPerformed

    private void CuentaBtn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn20ActionPerformed

    private void CuentaBtn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn22ActionPerformed

    private void CuentaBtn23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn23ActionPerformed

    private void CuentaBtn24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn24ActionPerformed

    private void SeguridadYAccesoBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguridadYAccesoBtn9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeguridadYAccesoBtn9ActionPerformed

    private void SeguridadYAccesoBtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguridadYAccesoBtn10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeguridadYAccesoBtn10ActionPerformed

    private void SeguridadYAccesoBtn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguridadYAccesoBtn11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeguridadYAccesoBtn11ActionPerformed

    private void SeguridadYAccesoBtn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguridadYAccesoBtn12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeguridadYAccesoBtn12ActionPerformed

    private void CuentaBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn4ActionPerformed

    private void CuentaBtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn10ActionPerformed

    private void CuentaBtn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn11ActionPerformed

    private void CuentaBtn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn12ActionPerformed

    private void PostearBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostearBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PostearBtn1ActionPerformed

    private void PostearBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostearBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PostearBtn2ActionPerformed

    private void PostearBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostearBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PostearBtn3ActionPerformed

    private void PostearBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostearBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PostearBtn4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busqueda1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ComunidadesBtn;
    private javax.swing.JButton CuentaBtn;
    private javax.swing.JButton CuentaBtn1;
    private javax.swing.JButton CuentaBtn10;
    private javax.swing.JButton CuentaBtn11;
    private javax.swing.JButton CuentaBtn12;
    private javax.swing.JButton CuentaBtn13;
    private javax.swing.JButton CuentaBtn14;
    private javax.swing.JButton CuentaBtn15;
    private javax.swing.JButton CuentaBtn16;
    private javax.swing.JButton CuentaBtn17;
    private javax.swing.JButton CuentaBtn18;
    private javax.swing.JButton CuentaBtn19;
    private javax.swing.JButton CuentaBtn2;
    private javax.swing.JButton CuentaBtn20;
    private javax.swing.JButton CuentaBtn22;
    private javax.swing.JButton CuentaBtn23;
    private javax.swing.JButton CuentaBtn24;
    private javax.swing.JButton CuentaBtn4;
    private javax.swing.JButton CuentaBtn5;
    private javax.swing.JButton CuentaBtn6;
    private javax.swing.JButton CuentaBtn7;
    private javax.swing.JButton ExplorarBtn;
    private javax.swing.JButton GuardadoBtn;
    private javax.swing.JLabel IdUsuario;
    private javax.swing.JButton InicioBtn;
    private javax.swing.JLabel NombreUsuario;
    private javax.swing.JButton NotificacionesBtn;
    private javax.swing.JButton PerfilBtn;
    private javax.swing.JButton PerfilBtn1;
    private javax.swing.JButton PerfilBtn2;
    private javax.swing.JButton PerfilBtn3;
    private javax.swing.JButton PerfilBtn4;
    private javax.swing.JPanel PerfilPanel;
    private javax.swing.JLabel Perfil_Img;
    private javax.swing.JButton PostearBtn;
    private javax.swing.JButton PostearBtn1;
    private javax.swing.JButton PostearBtn2;
    private javax.swing.JButton PostearBtn3;
    private javax.swing.JButton PostearBtn4;
    private javax.swing.JButton SeguridadYAccesoBtn;
    private javax.swing.JButton SeguridadYAccesoBtn10;
    private javax.swing.JButton SeguridadYAccesoBtn11;
    private javax.swing.JButton SeguridadYAccesoBtn12;
    private javax.swing.JButton SeguridadYAccesoBtn3;
    private javax.swing.JButton SeguridadYAccesoBtn4;
    private javax.swing.JButton SeguridadYAccesoBtn5;
    private javax.swing.JButton SeguridadYAccesoBtn6;
    private javax.swing.JButton SeguridadYAccesoBtn7;
    private javax.swing.JButton SeguridadYAccesoBtn8;
    private javax.swing.JButton SeguridadYAccesoBtn9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
