/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyect_y;

/**
 *
 * @author dafmo
 */
public class Configuracion extends javax.swing.JFrame {

    /**
     * Creates new form Configuracion
     */
    
    
    public Configuracion() {
        initComponents();
       //Creamos el objeto UIManager.setLookAndFeel();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jLabel44 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        InicioBtn = new javax.swing.JButton();
        ExplorarBtn = new javax.swing.JButton();
        ComunidadesBtn = new javax.swing.JButton();
        NotificacionesBtn = new javax.swing.JButton();
        GuardadoBtn = new javax.swing.JButton();
        PerfilBtn = new javax.swing.JButton();
        PostearBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        Buscador = new javax.swing.JTextField();
        PerfilPanel = new javax.swing.JPanel();
        Perfil_Img = new javax.swing.JLabel();
        NombreUsuario = new javax.swing.JLabel();
        IdUsuario = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        JPanelGeneraPanel = new javax.swing.JTabbedPane();
        InformacionCuentaPanel = new javax.swing.JPanel();
        PanelCuenta = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DesactivarCuentaBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        InfCuentaBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        CambiarPassBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        InfCuenta = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        AtrasBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        NomUserBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        UsuarioLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        CorreoBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TelefonoLabel = new javax.swing.JLabel();
        TelefonoBtn = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        PassPanel = new javax.swing.JPanel();
        NomUserPanel = new javax.swing.JPanel();
        TelefonoPanel = new javax.swing.JPanel();
        CorreoPanel = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        SeguridadPanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        UsuarioLabel2 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        UsuarioLabel4 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        UsuarioLabel3 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        L_PS_Title = new javax.swing.JLabel();
        SilenciarYBloquearBtn = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        TusPostBtn = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        ContenidoVesBtn = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        L_PS_Title1 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        TusPostBtn1 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        TusPostBtn2 = new javax.swing.JButton();
        CuentaBtn = new javax.swing.JButton();
        NotiFicacionesBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        SeguridadYAccesoBtn = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        PrivacidadYSeguridadBtn = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();

        jLabel44.setText("jLabel44");
        jTabbedPane2.addTab("tab1", jLabel44);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(26, 26, 29));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InicioBtn.setBackground(new java.awt.Color(26, 26, 29));
        InicioBtn.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        InicioBtn.setForeground(new java.awt.Color(204, 204, 204));
        InicioBtn.setText("   Inicio");
        InicioBtn.setToolTipText("");
        InicioBtn.setAlignmentY(0.0F);
        InicioBtn.setBorderPainted(false);
        InicioBtn.setContentAreaFilled(false);
        InicioBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        InicioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioBtnActionPerformed(evt);
            }
        });
        jPanel1.add(InicioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 200, 40));

        ExplorarBtn.setBackground(new java.awt.Color(26, 26, 29));
        ExplorarBtn.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        ExplorarBtn.setForeground(new java.awt.Color(204, 204, 204));
        ExplorarBtn.setText("  Explorar");
        ExplorarBtn.setToolTipText("");
        ExplorarBtn.setAlignmentY(0.0F);
        ExplorarBtn.setBorderPainted(false);
        ExplorarBtn.setContentAreaFilled(false);
        ExplorarBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(ExplorarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 200, 40));

        ComunidadesBtn.setBackground(new java.awt.Color(26, 26, 29));
        ComunidadesBtn.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        ComunidadesBtn.setForeground(new java.awt.Color(204, 204, 204));
        ComunidadesBtn.setText("  Comunidades");
        ComunidadesBtn.setToolTipText("");
        ComunidadesBtn.setAlignmentY(0.0F);
        ComunidadesBtn.setBorderPainted(false);
        ComunidadesBtn.setContentAreaFilled(false);
        ComunidadesBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ComunidadesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComunidadesBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ComunidadesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 200, 40));

        NotificacionesBtn.setBackground(new java.awt.Color(26, 26, 29));
        NotificacionesBtn.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        NotificacionesBtn.setForeground(new java.awt.Color(204, 204, 204));
        NotificacionesBtn.setText("  Notificaciones");
        NotificacionesBtn.setToolTipText("");
        NotificacionesBtn.setAlignmentY(0.0F);
        NotificacionesBtn.setBorderPainted(false);
        NotificacionesBtn.setContentAreaFilled(false);
        NotificacionesBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        NotificacionesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotificacionesBtnActionPerformed(evt);
            }
        });
        jPanel1.add(NotificacionesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 200, 40));

        GuardadoBtn.setBackground(new java.awt.Color(26, 26, 29));
        GuardadoBtn.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        GuardadoBtn.setForeground(new java.awt.Color(204, 204, 204));
        GuardadoBtn.setText("  Guardados");
        GuardadoBtn.setToolTipText("");
        GuardadoBtn.setAlignmentY(0.0F);
        GuardadoBtn.setBorderPainted(false);
        GuardadoBtn.setContentAreaFilled(false);
        GuardadoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        GuardadoBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        GuardadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardadoBtnActionPerformed(evt);
            }
        });
        jPanel1.add(GuardadoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 200, 40));

        PerfilBtn.setBackground(new java.awt.Color(26, 26, 29));
        PerfilBtn.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        PerfilBtn.setForeground(new java.awt.Color(204, 204, 204));
        PerfilBtn.setText("  Perfil");
        PerfilBtn.setToolTipText("");
        PerfilBtn.setAlignmentY(0.0F);
        PerfilBtn.setBorderPainted(false);
        PerfilBtn.setContentAreaFilled(false);
        PerfilBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PerfilBtn.setVerifyInputWhenFocusTarget(false);
        PerfilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilBtnActionPerformed(evt);
            }
        });
        jPanel1.add(PerfilBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 200, 40));

        PostearBtn.setBackground(new java.awt.Color(166, 77, 121));
        PostearBtn.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        PostearBtn.setForeground(new java.awt.Color(204, 204, 204));
        PostearBtn.setText("Publicacion");
        PostearBtn.setToolTipText("");
        PostearBtn.setAlignmentY(0.0F);
        PostearBtn.setBorderPainted(false);
        PostearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostearBtnActionPerformed(evt);
            }
        });
        jPanel1.add(PostearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 650, 200, 40));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 0, -1, 820));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 450, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Configuración");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 170, 30));

        Buscador.setBackground(new java.awt.Color(0, 0, 0));
        Buscador.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Buscador.setForeground(new java.awt.Color(204, 204, 204));
        Buscador.setText("Configuracion de la busqueda");
        jPanel1.add(Buscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 430, 50));
        Buscador.getAccessibleContext().setAccessibleName("Buscador");

        PerfilPanel.setBackground(new java.awt.Color(0, 0, 0));
        PerfilPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PerfilPanel.add(Perfil_Img, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 40));

        NombreUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        NombreUsuario.setForeground(new java.awt.Color(204, 204, 204));
        NombreUsuario.setText("Usuario Ejemplo");
        PerfilPanel.add(NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        IdUsuario.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        IdUsuario.setForeground(new java.awt.Color(106, 30, 85));
        IdUsuario.setText("@Usuario1");
        PerfilPanel.add(IdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jButton1.setBackground(new java.awt.Color(106, 30, 85));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(106, 30, 85));
        jButton1.setText("...");
        jButton1.setAlignmentY(0.0F);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        PerfilPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 50, 40));

        jPanel1.add(PerfilPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 720, 270, 60));

        jSeparator4.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator4.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 10, 820));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 450, 10));

        JPanelGeneraPanel.setBackground(new java.awt.Color(153, 153, 255));

        InformacionCuentaPanel.setBackground(new java.awt.Color(0, 0, 0));

        PanelCuenta.setBackground(new java.awt.Color(0, 0, 0));
        PanelCuenta.setPreferredSize(new java.awt.Dimension(610, 820));
        PanelCuenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Tu Cuenta");
        PanelCuenta.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Ve la información de la cuenta, u obtén más información acerca de las opciones ");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        PanelCuenta.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 510, 30));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("de desactivación de la cuenta");
        PanelCuenta.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 290, 30));

        DesactivarCuentaBtn.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        DesactivarCuentaBtn.setForeground(new java.awt.Color(204, 204, 204));
        DesactivarCuentaBtn.setText("Desactivar tu cuenta");
        DesactivarCuentaBtn.setBorderPainted(false);
        DesactivarCuentaBtn.setContentAreaFilled(false);
        DesactivarCuentaBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PanelCuenta.add(DesactivarCuentaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 550, 40));

        jLabel6.setFont(new java.awt.Font("Roboto Mono ExtraLight", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText(">");
        PanelCuenta.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, -1));

        InfCuentaBtn.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        InfCuentaBtn.setForeground(new java.awt.Color(204, 204, 204));
        InfCuentaBtn.setText("Informacion de la cuenta");
        InfCuentaBtn.setBorderPainted(false);
        InfCuentaBtn.setContentAreaFilled(false);
        InfCuentaBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        InfCuentaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfCuentaBtnActionPerformed(evt);
            }
        });
        PanelCuenta.add(InfCuentaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 550, 40));

        jLabel7.setFont(new java.awt.Font("Roboto Mono ExtraLight", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText(">");
        PanelCuenta.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, -1));

        CambiarPassBtn.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        CambiarPassBtn.setForeground(new java.awt.Color(204, 204, 204));
        CambiarPassBtn.setText("Cambia la contraseña");
        CambiarPassBtn.setBorderPainted(false);
        CambiarPassBtn.setContentAreaFilled(false);
        CambiarPassBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PanelCuenta.add(CambiarPassBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 550, 40));

        jLabel8.setFont(new java.awt.Font("Roboto Mono ExtraLight", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText(">");
        PanelCuenta.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

        InformacionCuentaPanel.add(PanelCuenta);

        JPanelGeneraPanel.addTab("Cuenta", InformacionCuentaPanel);

        InfCuenta.setBackground(new java.awt.Color(0, 0, 0));
        InfCuenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Informacion Cuenta");
        InfCuenta.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, 40));

        AtrasBtn.setBackground(new java.awt.Color(204, 204, 204));
        AtrasBtn.setFont(new java.awt.Font("Roboto Mono ExtraLight", 0, 24)); // NOI18N
        AtrasBtn.setForeground(new java.awt.Color(255, 255, 255));
        AtrasBtn.setText("<");
        AtrasBtn.setBorderPainted(false);
        AtrasBtn.setContentAreaFilled(false);
        AtrasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasBtnActionPerformed(evt);
            }
        });
        InfCuenta.add(AtrasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 23, 90, 30));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NomUserBtn.setBorderPainted(false);
        NomUserBtn.setContentAreaFilled(false);
        NomUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomUserBtnActionPerformed(evt);
            }
        });
        jPanel2.add(NomUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 600, 60));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Nombre de Usuario");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        UsuarioLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        UsuarioLabel.setForeground(new java.awt.Color(204, 204, 204));
        UsuarioLabel.setText("@Usuario");
        jPanel2.add(UsuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel12.setFont(new java.awt.Font("Roboto Mono ExtraLight", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText(">");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, -1, 50, 60));

        InfCuenta.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 610, 60));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Roboto Mono Light", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText(">");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, -1, 50, 60));

        CorreoBtn.setBorderPainted(false);
        CorreoBtn.setContentAreaFilled(false);
        CorreoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoBtnActionPerformed(evt);
            }
        });
        jPanel6.add(CorreoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 600, 60));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Correo Electronico");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        InfCuenta.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 610, 60));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Roboto Mono ExtraLight", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText(">");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, -1, 50, 60));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Telefono");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        TelefonoLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TelefonoLabel.setForeground(new java.awt.Color(204, 204, 204));
        TelefonoLabel.setText("+ 52 656 123 4567");
        jPanel5.add(TelefonoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        TelefonoBtn.setBorderPainted(false);
        TelefonoBtn.setContentAreaFilled(false);
        TelefonoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoBtnActionPerformed(evt);
            }
        });
        jPanel5.add(TelefonoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 600, 60));

        InfCuenta.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 610, 60));
        InfCuenta.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 610, 10));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("00 / 00 / 0000");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Creacion de la Cuenta");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        InfCuenta.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 610, 70));
        InfCuenta.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 610, -1));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("Fecha de nacimiento");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel25.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setText("00 / 00 / 0000");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        InfCuenta.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 610, 60));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Edad");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel24.setFont(new java.awt.Font("Roboto Mono ExtraLight", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setText(">");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, -1, 50, 60));

        jLabel28.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(166, 77, 121));
        jLabel28.setText("18");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 20, -1));

        InfCuenta.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 610, 60));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("País");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("México");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel20.setFont(new java.awt.Font("Roboto Mono ExtraLight", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText(">");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, -1, 50, 60));

        InfCuenta.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 610, 60));
        InfCuenta.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 610, 10));

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setOpaque(false);
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 204, 204));
        jLabel26.setText("Género");
        jPanel9.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel27.setFont(new java.awt.Font("Roboto Mono ExtraLight", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setText(">");
        jPanel9.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, -1, 50, 60));

        InfCuenta.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 610, 60));

        JPanelGeneraPanel.addTab("InfCuenta", InfCuenta);
        JPanelGeneraPanel.addTab("Pass", PassPanel);
        JPanelGeneraPanel.addTab("NomUser", NomUserPanel);
        JPanelGeneraPanel.addTab("Telefono", TelefonoPanel);
        JPanelGeneraPanel.addTab("Correo", CorreoPanel);
        JPanelGeneraPanel.addTab("Pais", jPanel10);
        JPanelGeneraPanel.addTab("Genero", jPanel11);
        JPanelGeneraPanel.addTab("Edad", jPanel12);

        SeguridadPanel.setBackground(new java.awt.Color(0, 0, 0));
        SeguridadPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("Administra la seguridad de tu cuenta y lleva un control de su uso, incluidas las aplicaciones ");
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        SeguridadPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 510, 30));

        jLabel29.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 204, 204));
        jLabel29.setText("que conectaste a ella.");
        SeguridadPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 290, 30));

        jLabel30.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(204, 204, 204));
        jLabel30.setText("Seguridad y acceso a la cuenta");
        SeguridadPanel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 25, 300, -1));

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));
        jPanel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setBackground(new java.awt.Color(0, 0, 0));
        jLabel33.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 204, 204));
        jLabel33.setText("Aplicaciones y sesiones");
        jPanel14.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 20));

        UsuarioLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        UsuarioLabel2.setForeground(new java.awt.Color(204, 204, 204));
        UsuarioLabel2.setText("cuenta y las aplicaciones que conectaste con ella.");
        jPanel14.add(UsuarioLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel34.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(204, 204, 204));
        jLabel34.setText(">");
        jPanel14.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, -1, 50, 60));

        UsuarioLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        UsuarioLabel4.setForeground(new java.awt.Color(204, 204, 204));
        UsuarioLabel4.setText("Consulta la informacion sobre cuando iniciaste sesion en tu ");
        jPanel14.add(UsuarioLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        SeguridadPanel.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 580, 60));

        jPanel15.setBackground(new java.awt.Color(0, 0, 0));
        jPanel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setBackground(new java.awt.Color(0, 0, 0));
        jLabel35.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 204, 204));
        jLabel35.setText("Seguridad");
        jPanel15.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 20));

        UsuarioLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        UsuarioLabel3.setForeground(new java.awt.Color(204, 204, 204));
        UsuarioLabel3.setText("Administra la seguridad de tu cuenta");
        jPanel15.add(UsuarioLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel36.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(204, 204, 204));
        jLabel36.setText(">");
        jPanel15.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, -1, 50, 60));

        SeguridadPanel.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 570, 60));

        JPanelGeneraPanel.addTab("Seguridad", SeguridadPanel);

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L_PS_Title.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        L_PS_Title.setForeground(new java.awt.Color(204, 204, 204));
        L_PS_Title.setText("Privacidad y seguridad");
        jPanel13.add(L_PS_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 25, 300, -1));

        SilenciarYBloquearBtn.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        SilenciarYBloquearBtn.setForeground(new java.awt.Color(204, 204, 204));
        SilenciarYBloquearBtn.setText("<html><p style=\"font-size: 10px; padding:  0px 0px 0px 30px;\"> Silenciar y bloquear</p>\n<br> <p style=\"font-size: 7 px; padding: 0px 0px 0px 30px; color: rgba(255,255,255,0.5);\"> Administra las cuentas y notificaciones que has silenciado o bloqueado</p>\n </html>");
        SilenciarYBloquearBtn.setBorderPainted(false);
        SilenciarYBloquearBtn.setContentAreaFilled(false);
        SilenciarYBloquearBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SilenciarYBloquearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SilenciarYBloquearBtnActionPerformed(evt);
            }
        });
        jPanel13.add(SilenciarYBloquearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 660, 60));

        jLabel40.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(204, 204, 204));
        jLabel40.setText("Administra qué información ves y compartes en Y.");
        jLabel40.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel13.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 510, 30));

        jLabel39.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText(">");
        jPanel13.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 210, 20, 50));

        jLabel37.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText(">");
        jPanel13.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 20, 50));

        TusPostBtn.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TusPostBtn.setForeground(new java.awt.Color(204, 204, 204));
        TusPostBtn.setText("<html><p style=\"font-size: 10px; padding:  0px 0px 0px 30px;\"> Tus publicaciones</p>\n<br> <p style=\"font-size: 7 px; padding: 0px 0px 0px 30px; color: rgba(255,255,255,0.5);\"> Administra la información asociada a tus publicaciones</p>\n </html>");
        TusPostBtn.setBorderPainted(false);
        TusPostBtn.setContentAreaFilled(false);
        TusPostBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TusPostBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TusPostBtnActionPerformed(evt);
            }
        });
        jPanel13.add(TusPostBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 650, 60));

        jLabel41.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText(">");
        jPanel13.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 20, 50));

        jLabel42.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText(">");
        jPanel13.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 20, 50));

        ContenidoVesBtn.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        ContenidoVesBtn.setForeground(new java.awt.Color(204, 204, 204));
        ContenidoVesBtn.setText("<html><p style=\"font-size: 10px; padding:  0px 0px 0px 30px;\"> Contenido que ves</p>\n<br> <p style=\"font-size: 7 px; padding: 0px 0px 0px 30px; color: rgba(255,255,255,0.5);\"> Decide lo que ves en Y según tus preferencias, como temas e intereses.</p>\n </html>");
        ContenidoVesBtn.setBorderPainted(false);
        ContenidoVesBtn.setContentAreaFilled(false);
        ContenidoVesBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ContenidoVesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContenidoVesBtnActionPerformed(evt);
            }
        });
        jPanel13.add(ContenidoVesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 650, 60));

        jLabel43.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText(">");
        jPanel13.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 20, 50));

        JPanelGeneraPanel.addTab("Privacidad", jPanel13);

        jPanel16.setBackground(new java.awt.Color(0, 0, 0));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L_PS_Title1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        L_PS_Title1.setForeground(new java.awt.Color(204, 204, 204));
        L_PS_Title1.setText("Notificaciones");
        jPanel16.add(L_PS_Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 25, 300, -1));

        jLabel46.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(204, 204, 204));
        jLabel46.setText("Selecciona los tipos de notificaciones que recibes sobre tus actividades, intereses y recomendaciones.");
        jLabel46.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel16.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 560, 30));

        TusPostBtn1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TusPostBtn1.setForeground(new java.awt.Color(204, 204, 204));
        TusPostBtn1.setText("<html><p style=\"font-size: 10px; padding:  0px 0px 0px 30px;\">Preferencias</p>\n<br> <p style=\"font-size: 7 px; padding: 0px 0px 0px 30px; color: rgba(255,255,255,0.5);\">Seleccione sus preferencias por tipo de notificación.</p>\n </html>");
        TusPostBtn1.setBorderPainted(false);
        TusPostBtn1.setContentAreaFilled(false);
        TusPostBtn1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TusPostBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TusPostBtn1ActionPerformed(evt);
            }
        });
        jPanel16.add(TusPostBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 650, 60));

        jLabel45.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(204, 204, 204));
        jLabel45.setText(">");
        jPanel16.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 50, 60));

        jLabel47.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(204, 204, 204));
        jLabel47.setText(">");
        jPanel16.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 50, 60));

        TusPostBtn2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TusPostBtn2.setForeground(new java.awt.Color(204, 204, 204));
        TusPostBtn2.setText("<html><p style=\"font-size: 10px; padding:  0px 0px 0px 30px;\"> Filtros</p>\n<br> <p style=\"font-size: 7 px; padding: 0px 0px 0px 30px; color: rgba(255,255,255,0.5);\">Elige las notificaciones que deseas ver y las que no.</p>\n </html>");
        TusPostBtn2.setBorderPainted(false);
        TusPostBtn2.setContentAreaFilled(false);
        TusPostBtn2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TusPostBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TusPostBtn2ActionPerformed(evt);
            }
        });
        jPanel16.add(TusPostBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 650, 60));

        JPanelGeneraPanel.addTab("Notificaciones", jPanel16);

        jPanel1.add(JPanelGeneraPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 660, 820));

        CuentaBtn.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        CuentaBtn.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn.setText("  Cuenta");
        CuentaBtn.setBorder(null);
        CuentaBtn.setBorderPainted(false);
        CuentaBtn.setContentAreaFilled(false);
        CuentaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 450, 50));

        NotiFicacionesBtn.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        NotiFicacionesBtn.setForeground(new java.awt.Color(204, 204, 204));
        NotiFicacionesBtn.setText(" Notificaciones ");
        NotiFicacionesBtn.setToolTipText("");
        NotiFicacionesBtn.setBorder(null);
        NotiFicacionesBtn.setBorderPainted(false);
        NotiFicacionesBtn.setContentAreaFilled(false);
        NotiFicacionesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NotiFicacionesBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        NotiFicacionesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotiFicacionesBtnActionPerformed(evt);
            }
        });
        jPanel1.add(NotiFicacionesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 450, 50));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(">");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 260, 20, 50));

        jLabel31.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText(">");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 112, 20, 50));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 450, 10));

        SeguridadYAccesoBtn.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        SeguridadYAccesoBtn.setForeground(new java.awt.Color(204, 204, 204));
        SeguridadYAccesoBtn.setText("  Seguridad y acceso a la cuenta ");
        SeguridadYAccesoBtn.setToolTipText("");
        SeguridadYAccesoBtn.setBorder(null);
        SeguridadYAccesoBtn.setBorderPainted(false);
        SeguridadYAccesoBtn.setContentAreaFilled(false);
        SeguridadYAccesoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SeguridadYAccesoBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeguridadYAccesoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguridadYAccesoBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SeguridadYAccesoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 450, 50));

        jLabel32.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText(">");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 160, 20, 50));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 450, 10));

        PrivacidadYSeguridadBtn.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        PrivacidadYSeguridadBtn.setForeground(new java.awt.Color(204, 204, 204));
        PrivacidadYSeguridadBtn.setText("  Privacidad y seguridad ");
        PrivacidadYSeguridadBtn.setToolTipText("");
        PrivacidadYSeguridadBtn.setBorder(null);
        PrivacidadYSeguridadBtn.setBorderPainted(false);
        PrivacidadYSeguridadBtn.setContentAreaFilled(false);
        PrivacidadYSeguridadBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PrivacidadYSeguridadBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PrivacidadYSeguridadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrivacidadYSeguridadBtnActionPerformed(evt);
            }
        });
        jPanel1.add(PrivacidadYSeguridadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 450, 50));

        jLabel38.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText(">");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 210, 20, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InicioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InicioBtnActionPerformed

    private void ComunidadesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComunidadesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComunidadesBtnActionPerformed

    private void NotificacionesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotificacionesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NotificacionesBtnActionPerformed

    private void GuardadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardadoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardadoBtnActionPerformed

    private void PerfilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerfilBtnActionPerformed

    private void PostearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostearBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PostearBtnActionPerformed

    private void CuentaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtnActionPerformed
        JPanelGeneraPanel.setSelectedIndex(0);
    }//GEN-LAST:event_CuentaBtnActionPerformed

    private void NotiFicacionesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotiFicacionesBtnActionPerformed
        JPanelGeneraPanel.setSelectedIndex(13);
    }//GEN-LAST:event_NotiFicacionesBtnActionPerformed

    private void SeguridadYAccesoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguridadYAccesoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeguridadYAccesoBtnActionPerformed

    private void PrivacidadYSeguridadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrivacidadYSeguridadBtnActionPerformed
        // TODO add your handling code here:
        JPanelGeneraPanel.setSelectedIndex(12);
    }//GEN-LAST:event_PrivacidadYSeguridadBtnActionPerformed

    private void ContenidoVesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContenidoVesBtnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ContenidoVesBtnActionPerformed

    private void TusPostBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TusPostBtnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TusPostBtnActionPerformed

    private void SilenciarYBloquearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SilenciarYBloquearBtnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_SilenciarYBloquearBtnActionPerformed

    private void TelefonoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoBtnActionPerformed
        JPanelGeneraPanel.setSelectedIndex(4);
    }//GEN-LAST:event_TelefonoBtnActionPerformed

    private void CorreoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoBtnActionPerformed
        JPanelGeneraPanel.setSelectedIndex(5);
    }//GEN-LAST:event_CorreoBtnActionPerformed

    private void NomUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomUserBtnActionPerformed
        JPanelGeneraPanel.setSelectedIndex(4);
    }//GEN-LAST:event_NomUserBtnActionPerformed

    private void AtrasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasBtnActionPerformed
        JPanelGeneraPanel.setSelectedIndex(0);
    }//GEN-LAST:event_AtrasBtnActionPerformed

    private void InfCuentaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfCuentaBtnActionPerformed
        JPanelGeneraPanel.setSelectedIndex(1);
    }//GEN-LAST:event_InfCuentaBtnActionPerformed

    private void TusPostBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TusPostBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TusPostBtn1ActionPerformed

    private void TusPostBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TusPostBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TusPostBtn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtrasBtn;
    private javax.swing.JTextField Buscador;
    private javax.swing.JButton CambiarPassBtn;
    private javax.swing.JButton ComunidadesBtn;
    private javax.swing.JButton ContenidoVesBtn;
    private javax.swing.JButton CorreoBtn;
    private javax.swing.JPanel CorreoPanel;
    private javax.swing.JButton CuentaBtn;
    private javax.swing.JButton DesactivarCuentaBtn;
    private javax.swing.JButton ExplorarBtn;
    private javax.swing.JButton GuardadoBtn;
    private javax.swing.JLabel IdUsuario;
    private javax.swing.JPanel InfCuenta;
    private javax.swing.JButton InfCuentaBtn;
    private javax.swing.JPanel InformacionCuentaPanel;
    private javax.swing.JButton InicioBtn;
    private javax.swing.JTabbedPane JPanelGeneraPanel;
    private javax.swing.JLabel L_PS_Title;
    private javax.swing.JLabel L_PS_Title1;
    private javax.swing.JButton NomUserBtn;
    private javax.swing.JPanel NomUserPanel;
    private javax.swing.JLabel NombreUsuario;
    private javax.swing.JButton NotiFicacionesBtn;
    private javax.swing.JButton NotificacionesBtn;
    private javax.swing.JPanel PanelCuenta;
    private javax.swing.JPanel PassPanel;
    private javax.swing.JButton PerfilBtn;
    private javax.swing.JPanel PerfilPanel;
    private javax.swing.JLabel Perfil_Img;
    private javax.swing.JButton PostearBtn;
    private javax.swing.JButton PrivacidadYSeguridadBtn;
    private javax.swing.JPanel SeguridadPanel;
    private javax.swing.JButton SeguridadYAccesoBtn;
    private javax.swing.JButton SilenciarYBloquearBtn;
    private javax.swing.JButton TelefonoBtn;
    private javax.swing.JLabel TelefonoLabel;
    private javax.swing.JPanel TelefonoPanel;
    private javax.swing.JButton TusPostBtn;
    private javax.swing.JButton TusPostBtn1;
    private javax.swing.JButton TusPostBtn2;
    private javax.swing.JLabel UsuarioLabel;
    private javax.swing.JLabel UsuarioLabel2;
    private javax.swing.JLabel UsuarioLabel3;
    private javax.swing.JLabel UsuarioLabel4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
