/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyect_y;

/**
 *
 * @author gisel
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public InicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        BG = new javax.swing.JPanel();
        PanelFLotante = new javax.swing.JPanel();
        L_Inicia = new javax.swing.JLabel();
        B_IniciaSApp = new javax.swing.JButton();
        SeparadorDer = new javax.swing.JSeparator();
        B_Registrate = new javax.swing.JButton();
        L_YaCuenta = new javax.swing.JLabel();
        SeparadorIzq = new javax.swing.JSeparator();
        LabelOR = new javax.swing.JLabel();
        B_RegisG = new javax.swing.JButton();
        B_Olvidar = new javax.swing.JButton();
        B_Siguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TP_Contra = new javax.swing.JTextPane();
        L_Correo = new javax.swing.JLabel();
        L_Contra = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TP_Correo = new javax.swing.JTextPane();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setSize(new java.awt.Dimension(1920, 1080));

        BG.setBackground(new java.awt.Color(0, 0, 0));

        PanelFLotante.setBackground(new java.awt.Color(26, 26, 29));

        L_Inicia.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        L_Inicia.setForeground(new java.awt.Color(255, 255, 255));
        L_Inicia.setText("Inicia Sesión en Y");

        B_IniciaSApp.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        B_IniciaSApp.setActionCommand("InicioSesionApple");
        B_IniciaSApp.setLabel("Inicia Sesión con Apple");
        B_IniciaSApp.setPreferredSize(new java.awt.Dimension(90, 25));
        B_IniciaSApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_IniciaSAppActionPerformed(evt);
            }
        });

        B_Registrate.setBackground(new java.awt.Color(26, 26, 29));
        B_Registrate.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        B_Registrate.setForeground(new java.awt.Color(166, 77, 121));
        B_Registrate.setActionCommand("Crea una Cuenta");
        B_Registrate.setBorder(null);
        B_Registrate.setBorderPainted(false);
        B_Registrate.setContentAreaFilled(false);
        B_Registrate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        B_Registrate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B_Registrate.setLabel("Regístrate");
        B_Registrate.setPreferredSize(new java.awt.Dimension(90, 25));
        B_Registrate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_RegistrateActionPerformed(evt);
            }
        });

        L_YaCuenta.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        L_YaCuenta.setForeground(new java.awt.Color(255, 255, 255));
        L_YaCuenta.setText("Aún no tienes una cuenta?");

        LabelOR.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        LabelOR.setForeground(new java.awt.Color(255, 255, 255));
        LabelOR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelOR.setText("o");

        B_RegisG.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        B_RegisG.setActionCommand("IniciaSG");
        B_RegisG.setLabel("Inicia Sesión con Google");
        B_RegisG.setPreferredSize(new java.awt.Dimension(90, 25));
        B_RegisG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_RegisGActionPerformed(evt);
            }
        });

        B_Olvidar.setBackground(new java.awt.Color(26, 26, 29));
        B_Olvidar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        B_Olvidar.setForeground(new java.awt.Color(255, 255, 255));
        B_Olvidar.setActionCommand("OlvContra");
        B_Olvidar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(166, 77, 121)));
        B_Olvidar.setLabel("¿Olvidaste tu contraseña?");
        B_Olvidar.setPreferredSize(new java.awt.Dimension(90, 25));
        B_Olvidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_OlvidarActionPerformed(evt);
            }
        });

        B_Siguiente.setBackground(new java.awt.Color(166, 77, 121));
        B_Siguiente.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        B_Siguiente.setForeground(new java.awt.Color(255, 255, 255));
        B_Siguiente.setActionCommand("Siguiente");
        B_Siguiente.setLabel("Siguiente");
        B_Siguiente.setPreferredSize(new java.awt.Dimension(90, 25));
        B_Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_SiguienteActionPerformed(evt);
            }
        });

        TP_Contra.setBackground(new java.awt.Color(26, 26, 29));
        TP_Contra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TP_Contra.setContentType("email"); // NOI18N
        TP_Contra.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        TP_Contra.setForeground(new java.awt.Color(166, 77, 121));
        TP_Contra.setText(" ");
        TP_Contra.setToolTipText("");
        TP_Contra.setName("Télefono"); // NOI18N
        jScrollPane1.setViewportView(TP_Contra);

        L_Correo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        L_Correo.setForeground(new java.awt.Color(255, 255, 255));
        L_Correo.setText("Télefono, correo o nombre de usuario");

        L_Contra.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        L_Contra.setForeground(new java.awt.Color(255, 255, 255));
        L_Contra.setText("Contraseña");

        TP_Correo.setBackground(new java.awt.Color(26, 26, 29));
        TP_Correo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TP_Correo.setContentType("email"); // NOI18N
        TP_Correo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        TP_Correo.setForeground(new java.awt.Color(166, 77, 121));
        TP_Correo.setToolTipText("");
        TP_Correo.setName("Télefono"); // NOI18N
        jScrollPane2.setViewportView(TP_Correo);

        javax.swing.GroupLayout PanelFLotanteLayout = new javax.swing.GroupLayout(PanelFLotante);
        PanelFLotante.setLayout(PanelFLotanteLayout);
        PanelFLotanteLayout.setHorizontalGroup(
            PanelFLotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFLotanteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(L_Inicia)
                .addGap(181, 181, 181))
            .addGroup(PanelFLotanteLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(PanelFLotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFLotanteLayout.createSequentialGroup()
                        .addGroup(PanelFLotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelFLotanteLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(L_YaCuenta)
                                .addGap(18, 18, 18)
                                .addComponent(B_Registrate, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(B_IniciaSApp, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_RegisG, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(139, Short.MAX_VALUE))
                    .addGroup(PanelFLotanteLayout.createSequentialGroup()
                        .addGroup(PanelFLotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_Contra)
                            .addComponent(L_Correo)
                            .addComponent(B_Olvidar, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelFLotanteLayout.createSequentialGroup()
                                .addComponent(SeparadorIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelOR, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SeparadorDer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(B_Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PanelFLotanteLayout.setVerticalGroup(
            PanelFLotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFLotanteLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(L_Inicia)
                .addGap(18, 18, 18)
                .addComponent(B_RegisG, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B_IniciaSApp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelFLotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelOR, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeparadorIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeparadorDer, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L_Contra, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(B_Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_Olvidar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(PanelFLotanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_YaCuenta)
                    .addComponent(B_Registrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        B_IniciaSApp.getAccessibleContext().setAccessibleName("InicioSApp");
        B_Olvidar.getAccessibleContext().setAccessibleName("OlvContra");

        javax.swing.GroupLayout BGLayout = new javax.swing.GroupLayout(BG);
        BG.setLayout(BGLayout);
        BGLayout.setHorizontalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addGap(466, 466, 466)
                .addComponent(PanelFLotante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(479, Short.MAX_VALUE))
        );
        BGLayout.setVerticalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(PanelFLotante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        PanelFLotante.getAccessibleContext().setAccessibleName("PanelFlot");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_OlvidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_OlvidarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_OlvidarActionPerformed

    private void B_RegisGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RegisGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_RegisGActionPerformed

    private void B_RegistrateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RegistrateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_RegistrateActionPerformed

    private void B_IniciaSAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_IniciaSAppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_IniciaSAppActionPerformed

    private void B_SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_SiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_SiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JButton B_IniciaSApp;
    private javax.swing.JButton B_Olvidar;
    private javax.swing.JButton B_RegisG;
    private javax.swing.JButton B_Registrate;
    private javax.swing.JButton B_Siguiente;
    private javax.swing.JLabel L_Contra;
    private javax.swing.JLabel L_Correo;
    private javax.swing.JLabel L_Inicia;
    private javax.swing.JLabel L_YaCuenta;
    private javax.swing.JLabel LabelOR;
    private javax.swing.JPanel PanelFLotante;
    private javax.swing.JSeparator SeparadorDer;
    private javax.swing.JSeparator SeparadorIzq;
    private javax.swing.JTextPane TP_Contra;
    private javax.swing.JTextPane TP_Correo;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
