/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyect_y;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author gisel
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Inicio() {
        initComponents();
        
        String url="src/main/java/Multimedia/YSinFondo.png";
        ImageIcon image = new ImageIcon(url);
        Image img = image.getImage().getScaledInstance(550,550, Image.SCALE_DEFAULT );
        ImageIcon icono = new ImageIcon(img);
        L_in.setIcon(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        BG = new javax.swing.JPanel();
        L_LoQuePAsa = new javax.swing.JLabel();
        B_RegisApp = new javax.swing.JButton();
        B_CreaCuenta = new javax.swing.JButton();
        LabelOR = new javax.swing.JLabel();
        SeparadorDer = new javax.swing.JSeparator();
        SeparadorIzq = new javax.swing.JSeparator();
        L_UneteHoy = new javax.swing.JLabel();
        L_PrivCookies = new javax.swing.JLabel();
        B_RegisG = new javax.swing.JButton();
        L_YaCuenta = new javax.swing.JLabel();
        B_IniciaS = new javax.swing.JButton();
        L_in = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setSize(new java.awt.Dimension(1920, 1080));

        BG.setBackground(new java.awt.Color(0, 0, 0));
        BG.setAlignmentX(188.0F);
        BG.setAlignmentY(48.0F);
        BG.setPreferredSize(new java.awt.Dimension(1920, 1080));

        L_LoQuePAsa.setFont(new java.awt.Font("Arial Black", 1, 64)); // NOI18N
        L_LoQuePAsa.setForeground(new java.awt.Color(255, 255, 255));
        L_LoQuePAsa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        L_LoQuePAsa.setText("<html>Lo que está pasando ahora <html> ");

        B_RegisApp.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        B_RegisApp.setLabel("Registrarse con Apple");
        B_RegisApp.setPreferredSize(new java.awt.Dimension(90, 25));
        B_RegisApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_RegisAppActionPerformed(evt);
            }
        });

        B_CreaCuenta.setBackground(new java.awt.Color(166, 77, 121));
        B_CreaCuenta.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        B_CreaCuenta.setForeground(new java.awt.Color(255, 255, 255));
        B_CreaCuenta.setActionCommand("Crea una Cuenta");
        B_CreaCuenta.setLabel("Crea una cuenta");
        B_CreaCuenta.setPreferredSize(new java.awt.Dimension(90, 25));
        B_CreaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CreaCuentaActionPerformed(evt);
            }
        });

        LabelOR.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        LabelOR.setForeground(new java.awt.Color(255, 255, 255));
        LabelOR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelOR.setText("o");

        L_UneteHoy.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        L_UneteHoy.setForeground(new java.awt.Color(255, 255, 255));
        L_UneteHoy.setText("Únete Hoy");

        L_PrivCookies.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        L_PrivCookies.setForeground(new java.awt.Color(255, 255, 255));
        L_PrivCookies.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        L_PrivCookies.setText("<html>Al registrarte, aceptas los Términos de servicio y la Política de privacidad, incluida la política de Uso de Cookies. <html>");

        B_RegisG.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        B_RegisG.setLabel("Registrarse con Google");
        B_RegisG.setPreferredSize(new java.awt.Dimension(90, 25));
        B_RegisG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_RegisGActionPerformed(evt);
            }
        });

        L_YaCuenta.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        L_YaCuenta.setForeground(new java.awt.Color(255, 255, 255));
        L_YaCuenta.setText("Ya tienes una cuenta?");

        B_IniciaS.setBackground(new java.awt.Color(26, 26, 29));
        B_IniciaS.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        B_IniciaS.setForeground(new java.awt.Color(166, 77, 121));
        B_IniciaS.setActionCommand("Crea una Cuenta");
        B_IniciaS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(166, 77, 121)));
        B_IniciaS.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        B_IniciaS.setLabel("Inicia Sesion");
        B_IniciaS.setPreferredSize(new java.awt.Dimension(90, 25));
        B_IniciaS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_IniciaSActionPerformed(evt);
            }
        });

        L_in.setText("jLabel1");

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Sobre");

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Descarga la aplicación de Y");

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Ayuda");

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Terminos de Servicio");

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Política de Privacidad");

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("© 2025 Y Corp.");

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Accesibilidad");

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Blogs");

        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Informacion sobre los anuncios");

        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Marketing");

        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Carreras");

        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Ajustes");

        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Y para negocios");

        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Anunciate");

        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Desarrolladores");

        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Directorio");

        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Política de Cookies");

        javax.swing.GroupLayout BGLayout = new javax.swing.GroupLayout(BG);
        BG.setLayout(BGLayout);
        BGLayout.setHorizontalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BGLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(L_in, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_LoQuePAsa, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_IniciaS, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_YaCuenta)
                            .addComponent(B_RegisG, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_PrivCookies, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_CreaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_UneteHoy)
                            .addComponent(B_RegisApp, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BGLayout.createSequentialGroup()
                                .addComponent(SeparadorIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelOR, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SeparadorDer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(BGLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addGroup(BGLayout.createSequentialGroup()
                        .addGap(715, 715, 715)
                        .addComponent(jLabel6)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        BGLayout.setVerticalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(L_LoQuePAsa, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(L_UneteHoy)
                .addGap(26, 26, 26)
                .addComponent(B_RegisG, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BGLayout.createSequentialGroup()
                        .addComponent(B_RegisApp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SeparadorIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SeparadorDer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LabelOR, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(B_CreaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L_PrivCookies, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(L_YaCuenta)
                .addGap(18, 18, 18)
                .addComponent(B_IniciaS, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(BGLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(L_in, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(9, 9, 9))
        );

        B_RegisApp.getAccessibleContext().setAccessibleName("InicioS");
        B_CreaCuenta.getAccessibleContext().setAccessibleName("Crea una Cuenta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, 1550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_IniciaSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_IniciaSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_IniciaSActionPerformed

    private void B_RegisGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RegisGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_RegisGActionPerformed

    private void B_CreaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CreaCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_CreaCuentaActionPerformed

    private void B_RegisAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RegisAppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_RegisAppActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JButton B_CreaCuenta;
    private javax.swing.JButton B_IniciaS;
    private javax.swing.JButton B_RegisApp;
    private javax.swing.JButton B_RegisG;
    private javax.swing.JLabel L_LoQuePAsa;
    private javax.swing.JLabel L_PrivCookies;
    private javax.swing.JLabel L_UneteHoy;
    private javax.swing.JLabel L_YaCuenta;
    private javax.swing.JLabel L_in;
    private javax.swing.JLabel LabelOR;
    private javax.swing.JSeparator SeparadorDer;
    private javax.swing.JSeparator SeparadorIzq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
