/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyect_y;

/**
 *
 * @author gisel
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        BG = new javax.swing.JPanel();
        L_LoQuePAsa = new javax.swing.JLabel();
        B_RegisApp = new javax.swing.JButton();
        B_CreaCuenta = new javax.swing.JButton();
        LabelOR = new javax.swing.JLabel();
        SeparadorDer = new javax.swing.JSeparator();
        SeparadorIzq = new javax.swing.JSeparator();
        L_UneteHoy = new javax.swing.JLabel();
        L_PrivCookies = new javax.swing.JLabel();
        B_RegisG = new javax.swing.JButton();
        L_YaCuenta = new javax.swing.JLabel();
        B_IniciaS = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setSize(new java.awt.Dimension(1920, 1080));

        BG.setBackground(new java.awt.Color(0, 0, 0));
        BG.setAlignmentX(188.0F);
        BG.setAlignmentY(48.0F);
        BG.setPreferredSize(new java.awt.Dimension(1920, 1080));

        L_LoQuePAsa.setFont(new java.awt.Font("Arial Black", 1, 64)); // NOI18N
        L_LoQuePAsa.setForeground(new java.awt.Color(255, 255, 255));
        L_LoQuePAsa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        L_LoQuePAsa.setText("<html>Lo que está pasando ahora <html> ");

        B_RegisApp.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        B_RegisApp.setLabel("Registrarse con Apple");
        B_RegisApp.setPreferredSize(new java.awt.Dimension(90, 25));
        B_RegisApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_RegisAppActionPerformed(evt);
            }
        });

        B_CreaCuenta.setBackground(new java.awt.Color(166, 77, 121));
        B_CreaCuenta.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        B_CreaCuenta.setForeground(new java.awt.Color(255, 255, 255));
        B_CreaCuenta.setActionCommand("Crea una Cuenta");
        B_CreaCuenta.setLabel("Crea una cuenta");
        B_CreaCuenta.setPreferredSize(new java.awt.Dimension(90, 25));
        B_CreaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CreaCuentaActionPerformed(evt);
            }
        });

        LabelOR.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        LabelOR.setForeground(new java.awt.Color(255, 255, 255));
        LabelOR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelOR.setText("o");

        L_UneteHoy.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        L_UneteHoy.setForeground(new java.awt.Color(255, 255, 255));
        L_UneteHoy.setText("Únete Hoy");

        L_PrivCookies.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        L_PrivCookies.setForeground(new java.awt.Color(255, 255, 255));
        L_PrivCookies.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        L_PrivCookies.setText("<html>Al registrarte, aceptas los Términos de servicio y la Política de privacidad, incluida la política de Uso de Cookies. <html>");

        B_RegisG.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        B_RegisG.setLabel("Registrarse con Google");
        B_RegisG.setPreferredSize(new java.awt.Dimension(90, 25));
        B_RegisG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_RegisGActionPerformed(evt);
            }
        });

        L_YaCuenta.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        L_YaCuenta.setForeground(new java.awt.Color(255, 255, 255));
        L_YaCuenta.setText("Ya tienes una cuenta?");

        B_IniciaS.setBackground(new java.awt.Color(26, 26, 29));
        B_IniciaS.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        B_IniciaS.setForeground(new java.awt.Color(166, 77, 121));
        B_IniciaS.setActionCommand("Crea una Cuenta");
        B_IniciaS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(166, 77, 121)));
        B_IniciaS.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        B_IniciaS.setLabel("Inicia Sesion");
        B_IniciaS.setPreferredSize(new java.awt.Dimension(90, 25));
        B_IniciaS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_IniciaSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BGLayout = new javax.swing.GroupLayout(BG);
        BG.setLayout(BGLayout);
        BGLayout.setHorizontalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addGap(776, 776, 776)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_IniciaS, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_YaCuenta)
                    .addComponent(B_RegisG, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_PrivCookies, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_CreaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_UneteHoy)
                    .addComponent(B_RegisApp, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BGLayout.createSequentialGroup()
                        .addComponent(SeparadorIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelOR, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SeparadorDer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(415, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BGLayout.createSequentialGroup()
                .addContainerGap(764, Short.MAX_VALUE)
                .addComponent(L_LoQuePAsa, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        BGLayout.setVerticalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(L_LoQuePAsa, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(L_UneteHoy)
                .addGap(29, 29, 29)
                .addComponent(B_RegisG, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BGLayout.createSequentialGroup()
                        .addComponent(B_RegisApp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SeparadorIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SeparadorDer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LabelOR, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_CreaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L_PrivCookies, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(L_YaCuenta)
                .addGap(18, 18, 18)
                .addComponent(B_IniciaS, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        B_RegisApp.getAccessibleContext().setAccessibleName("InicioS");
        B_CreaCuenta.getAccessibleContext().setAccessibleName("Crea una Cuenta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, 1521, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_RegisAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RegisAppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_RegisAppActionPerformed

    private void B_CreaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CreaCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_CreaCuentaActionPerformed

    private void B_RegisGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RegisGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_RegisGActionPerformed

    private void B_IniciaSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_IniciaSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_IniciaSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JButton B_CreaCuenta;
    private javax.swing.JButton B_IniciaS;
    private javax.swing.JButton B_RegisApp;
    private javax.swing.JButton B_RegisG;
    private javax.swing.JLabel L_LoQuePAsa;
    private javax.swing.JLabel L_PrivCookies;
    private javax.swing.JLabel L_UneteHoy;
    private javax.swing.JLabel L_YaCuenta;
    private javax.swing.JLabel LabelOR;
    private javax.swing.JSeparator SeparadorDer;
    private javax.swing.JSeparator SeparadorIzq;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
