/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyect_y;

/**
 *
 * @author Kevin G
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Principal
     */
    public Menu_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        InicioBtn = new javax.swing.JButton();
        ExplorarBtn = new javax.swing.JButton();
        ComunidadesBtn = new javax.swing.JButton();
        NotificacionesBtn = new javax.swing.JButton();
        GuardadoBtn = new javax.swing.JButton();
        PerfilBtn = new javax.swing.JButton();
        PostearBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        PerfilPanel = new javax.swing.JPanel();
        Perfil_Img = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        CuentaBtn = new javax.swing.JButton();
        SeguridadYAccesoBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PerfilBtn1 = new javax.swing.JButton();
        PerfilBtn2 = new javax.swing.JButton();
        PerfilBtn3 = new javax.swing.JButton();
        PerfilBtn4 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        SeguridadYAccesoBtn2 = new javax.swing.JButton();
        CuentaBtn1 = new javax.swing.JButton();
        CuentaBtn4 = new javax.swing.JButton();
        CuentaBtn5 = new javax.swing.JButton();
        CuentaBtn7 = new javax.swing.JButton();
        SeguridadYAccesoBtn3 = new javax.swing.JButton();
        SeguridadYAccesoBtn4 = new javax.swing.JButton();
        SeguridadYAccesoBtn5 = new javax.swing.JButton();
        SeguridadYAccesoBtn6 = new javax.swing.JButton();
        SeguridadYAccesoBtn7 = new javax.swing.JButton();
        SeguridadYAccesoBtn8 = new javax.swing.JButton();
        IdUsuario = new javax.swing.JLabel();
        NombreUsuario = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        CuentaBtn8 = new javax.swing.JButton();
        CuentaBtn9 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        CuentaBtn10 = new javax.swing.JButton();
        CuentaBtn11 = new javax.swing.JButton();
        CuentaBtn12 = new javax.swing.JButton();
        CuentaBtn13 = new javax.swing.JButton();
        CuentaBtn14 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        CuentaBtn15 = new javax.swing.JButton();
        CuentaBtn16 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        CuentaBtn17 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        CuentaBtn2 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        CuentaBtn6 = new javax.swing.JButton();
        CuentaBtn18 = new javax.swing.JButton();
        CuentaBtn19 = new javax.swing.JButton();
        CuentaBtn3 = new javax.swing.JButton();
        CuentaBtn20 = new javax.swing.JButton();
        CuentaBtn21 = new javax.swing.JButton();
        CuentaBtn22 = new javax.swing.JButton();
        CuentaBtn23 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        CuentaBtn24 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InicioBtn.setBackground(new java.awt.Color(26, 26, 29));
        InicioBtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        InicioBtn.setForeground(new java.awt.Color(204, 204, 204));
        InicioBtn.setText("  🏚Inicio");
        InicioBtn.setToolTipText("");
        InicioBtn.setAlignmentY(0.0F);
        InicioBtn.setBorderPainted(false);
        InicioBtn.setContentAreaFilled(false);
        InicioBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        InicioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioBtnActionPerformed(evt);
            }
        });
        jPanel1.add(InicioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 200, 40));

        ExplorarBtn.setBackground(new java.awt.Color(26, 26, 29));
        ExplorarBtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        ExplorarBtn.setForeground(new java.awt.Color(204, 204, 204));
        ExplorarBtn.setText("  🔍Explorar");
        ExplorarBtn.setToolTipText("");
        ExplorarBtn.setAlignmentY(0.0F);
        ExplorarBtn.setBorderPainted(false);
        ExplorarBtn.setContentAreaFilled(false);
        ExplorarBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ExplorarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExplorarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ExplorarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 200, 40));

        ComunidadesBtn.setBackground(new java.awt.Color(26, 26, 29));
        ComunidadesBtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        ComunidadesBtn.setForeground(new java.awt.Color(204, 204, 204));
        ComunidadesBtn.setText("  Mensajes");
        ComunidadesBtn.setToolTipText("");
        ComunidadesBtn.setAlignmentY(0.0F);
        ComunidadesBtn.setBorderPainted(false);
        ComunidadesBtn.setContentAreaFilled(false);
        ComunidadesBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ComunidadesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComunidadesBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ComunidadesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 200, 40));

        NotificacionesBtn.setBackground(new java.awt.Color(26, 26, 29));
        NotificacionesBtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        NotificacionesBtn.setForeground(new java.awt.Color(204, 204, 204));
        NotificacionesBtn.setText("  Notificaciones");
        NotificacionesBtn.setToolTipText("");
        NotificacionesBtn.setAlignmentY(0.0F);
        NotificacionesBtn.setBorderPainted(false);
        NotificacionesBtn.setContentAreaFilled(false);
        NotificacionesBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        NotificacionesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotificacionesBtnActionPerformed(evt);
            }
        });
        jPanel1.add(NotificacionesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 200, 40));

        GuardadoBtn.setBackground(new java.awt.Color(26, 26, 29));
        GuardadoBtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        GuardadoBtn.setForeground(new java.awt.Color(204, 204, 204));
        GuardadoBtn.setText("  Listas");
        GuardadoBtn.setToolTipText("");
        GuardadoBtn.setAlignmentY(0.0F);
        GuardadoBtn.setBorderPainted(false);
        GuardadoBtn.setContentAreaFilled(false);
        GuardadoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        GuardadoBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        GuardadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardadoBtnActionPerformed(evt);
            }
        });
        jPanel1.add(GuardadoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 200, 40));

        PerfilBtn.setBackground(new java.awt.Color(26, 26, 29));
        PerfilBtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        PerfilBtn.setForeground(new java.awt.Color(204, 204, 204));
        PerfilBtn.setText("  Mas");
        PerfilBtn.setToolTipText("");
        PerfilBtn.setAlignmentY(0.0F);
        PerfilBtn.setBorderPainted(false);
        PerfilBtn.setContentAreaFilled(false);
        PerfilBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PerfilBtn.setVerifyInputWhenFocusTarget(false);
        PerfilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilBtnActionPerformed(evt);
            }
        });
        jPanel1.add(PerfilBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, 200, 40));

        PostearBtn.setBackground(new java.awt.Color(166, 77, 121));
        PostearBtn.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        PostearBtn.setForeground(new java.awt.Color(204, 204, 204));
        PostearBtn.setText(" Exponer");
        PostearBtn.setToolTipText("");
        PostearBtn.setAlignmentY(0.0F);
        PostearBtn.setBorderPainted(false);
        PostearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostearBtnActionPerformed(evt);
            }
        });
        jPanel1.add(PostearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 920, 200, 40));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 0, -1, 1040));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 570, 490, -1));

        PerfilPanel.setBackground(new java.awt.Color(0, 0, 0));
        PerfilPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PerfilPanel.add(Perfil_Img, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 40));

        jPanel1.add(PerfilPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 720, 270, 60));

        jSeparator4.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator4.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 10, 1040));

        CuentaBtn.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        CuentaBtn.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn.setText("1000 publicaciones");
        CuentaBtn.setBorder(null);
        CuentaBtn.setBorderPainted(false);
        CuentaBtn.setContentAreaFilled(false);
        CuentaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 480, 100, 50));

        SeguridadYAccesoBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        SeguridadYAccesoBtn.setForeground(new java.awt.Color(204, 204, 204));
        SeguridadYAccesoBtn.setText("Le gusta");
        SeguridadYAccesoBtn.setToolTipText("");
        SeguridadYAccesoBtn.setBorder(null);
        SeguridadYAccesoBtn.setBorderPainted(false);
        SeguridadYAccesoBtn.setContentAreaFilled(false);
        SeguridadYAccesoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SeguridadYAccesoBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeguridadYAccesoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguridadYAccesoBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SeguridadYAccesoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 550, 70, 20));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<-");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 40, 50));

        PerfilBtn1.setBackground(new java.awt.Color(26, 26, 29));
        PerfilBtn1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        PerfilBtn1.setForeground(new java.awt.Color(204, 204, 204));
        PerfilBtn1.setText("  Marcadores");
        PerfilBtn1.setToolTipText("");
        PerfilBtn1.setAlignmentY(0.0F);
        PerfilBtn1.setBorderPainted(false);
        PerfilBtn1.setContentAreaFilled(false);
        PerfilBtn1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PerfilBtn1.setVerifyInputWhenFocusTarget(false);
        PerfilBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(PerfilBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 200, 40));

        PerfilBtn2.setBackground(new java.awt.Color(26, 26, 29));
        PerfilBtn2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        PerfilBtn2.setForeground(new java.awt.Color(204, 204, 204));
        PerfilBtn2.setText("  Trabajos");
        PerfilBtn2.setToolTipText("");
        PerfilBtn2.setAlignmentY(0.0F);
        PerfilBtn2.setBorderPainted(false);
        PerfilBtn2.setContentAreaFilled(false);
        PerfilBtn2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PerfilBtn2.setVerifyInputWhenFocusTarget(false);
        PerfilBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilBtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(PerfilBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 200, 40));

        PerfilBtn3.setBackground(new java.awt.Color(26, 26, 29));
        PerfilBtn3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        PerfilBtn3.setForeground(new java.awt.Color(204, 204, 204));
        PerfilBtn3.setText("  Comunidad");
        PerfilBtn3.setToolTipText("");
        PerfilBtn3.setAlignmentY(0.0F);
        PerfilBtn3.setBorderPainted(false);
        PerfilBtn3.setContentAreaFilled(false);
        PerfilBtn3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PerfilBtn3.setVerifyInputWhenFocusTarget(false);
        PerfilBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilBtn3ActionPerformed(evt);
            }
        });
        jPanel1.add(PerfilBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 200, 40));

        PerfilBtn4.setBackground(new java.awt.Color(26, 26, 29));
        PerfilBtn4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        PerfilBtn4.setForeground(new java.awt.Color(204, 204, 204));
        PerfilBtn4.setText("  Perfil");
        PerfilBtn4.setToolTipText("");
        PerfilBtn4.setAlignmentY(0.0F);
        PerfilBtn4.setBorderPainted(false);
        PerfilBtn4.setContentAreaFilled(false);
        PerfilBtn4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PerfilBtn4.setVerifyInputWhenFocusTarget(false);
        PerfilBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilBtn4ActionPerformed(evt);
            }
        });
        jPanel1.add(PerfilBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 200, 40));

        jLabel37.setFont(new java.awt.Font("Roboto Black", 1, 22)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(204, 204, 204));
        jLabel37.setText("Usuario");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 170, 30));

        jPanel13.setBackground(new java.awt.Color(65, 63, 63));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 490, 190));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Editar perfil");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 280, -1, -1));

        jLabel38.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(204, 204, 204));
        jLabel38.setText("Qué pasa");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 350, 210, 30));

        SeguridadYAccesoBtn2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        SeguridadYAccesoBtn2.setForeground(new java.awt.Color(204, 204, 204));
        SeguridadYAccesoBtn2.setText("0 publicaciones");
        SeguridadYAccesoBtn2.setToolTipText("");
        SeguridadYAccesoBtn2.setBorder(null);
        SeguridadYAccesoBtn2.setBorderPainted(false);
        SeguridadYAccesoBtn2.setContentAreaFilled(false);
        SeguridadYAccesoBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SeguridadYAccesoBtn2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeguridadYAccesoBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguridadYAccesoBtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(SeguridadYAccesoBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 100, 50));

        CuentaBtn1.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        CuentaBtn1.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn1.setText("🗓Se unio en mes y año");
        CuentaBtn1.setBorder(null);
        CuentaBtn1.setBorderPainted(false);
        CuentaBtn1.setContentAreaFilled(false);
        CuentaBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 450, 50));

        CuentaBtn4.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        CuentaBtn4.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn4.setText("**");
        CuentaBtn4.setBorder(null);
        CuentaBtn4.setBorderPainted(false);
        CuentaBtn4.setContentAreaFilled(false);
        CuentaBtn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn4ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 80, 50));

        CuentaBtn5.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        CuentaBtn5.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn5.setText("0");
        CuentaBtn5.setBorder(null);
        CuentaBtn5.setBorderPainted(false);
        CuentaBtn5.setContentAreaFilled(false);
        CuentaBtn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn5ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 80, 50));

        CuentaBtn7.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        CuentaBtn7.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn7.setText("00000");
        CuentaBtn7.setBorder(null);
        CuentaBtn7.setBorderPainted(false);
        CuentaBtn7.setContentAreaFilled(false);
        CuentaBtn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn7ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 220, 80, 50));

        SeguridadYAccesoBtn3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        SeguridadYAccesoBtn3.setForeground(new java.awt.Color(204, 204, 204));
        SeguridadYAccesoBtn3.setText("@Usuario");
        SeguridadYAccesoBtn3.setToolTipText("");
        SeguridadYAccesoBtn3.setBorder(null);
        SeguridadYAccesoBtn3.setBorderPainted(false);
        SeguridadYAccesoBtn3.setContentAreaFilled(false);
        SeguridadYAccesoBtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SeguridadYAccesoBtn3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeguridadYAccesoBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguridadYAccesoBtn3ActionPerformed(evt);
            }
        });
        jPanel1.add(SeguridadYAccesoBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 100, 50));

        SeguridadYAccesoBtn4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        SeguridadYAccesoBtn4.setForeground(new java.awt.Color(204, 204, 204));
        SeguridadYAccesoBtn4.setText("Mensajes");
        SeguridadYAccesoBtn4.setToolTipText("");
        SeguridadYAccesoBtn4.setBorder(null);
        SeguridadYAccesoBtn4.setBorderPainted(false);
        SeguridadYAccesoBtn4.setContentAreaFilled(false);
        SeguridadYAccesoBtn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SeguridadYAccesoBtn4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeguridadYAccesoBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguridadYAccesoBtn4ActionPerformed(evt);
            }
        });
        jPanel1.add(SeguridadYAccesoBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, 70, 20));

        SeguridadYAccesoBtn5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        SeguridadYAccesoBtn5.setForeground(new java.awt.Color(204, 204, 204));
        SeguridadYAccesoBtn5.setText("Respuestas");
        SeguridadYAccesoBtn5.setToolTipText("");
        SeguridadYAccesoBtn5.setBorder(null);
        SeguridadYAccesoBtn5.setBorderPainted(false);
        SeguridadYAccesoBtn5.setContentAreaFilled(false);
        SeguridadYAccesoBtn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SeguridadYAccesoBtn5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeguridadYAccesoBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguridadYAccesoBtn5ActionPerformed(evt);
            }
        });
        jPanel1.add(SeguridadYAccesoBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, 90, 20));

        SeguridadYAccesoBtn6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        SeguridadYAccesoBtn6.setForeground(new java.awt.Color(204, 204, 204));
        SeguridadYAccesoBtn6.setText("Resúmenes");
        SeguridadYAccesoBtn6.setToolTipText("");
        SeguridadYAccesoBtn6.setBorder(null);
        SeguridadYAccesoBtn6.setBorderPainted(false);
        SeguridadYAccesoBtn6.setContentAreaFilled(false);
        SeguridadYAccesoBtn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SeguridadYAccesoBtn6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeguridadYAccesoBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguridadYAccesoBtn6ActionPerformed(evt);
            }
        });
        jPanel1.add(SeguridadYAccesoBtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 550, 90, 20));

        SeguridadYAccesoBtn7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        SeguridadYAccesoBtn7.setForeground(new java.awt.Color(204, 204, 204));
        SeguridadYAccesoBtn7.setText("Artículos");
        SeguridadYAccesoBtn7.setToolTipText("");
        SeguridadYAccesoBtn7.setBorder(null);
        SeguridadYAccesoBtn7.setBorderPainted(false);
        SeguridadYAccesoBtn7.setContentAreaFilled(false);
        SeguridadYAccesoBtn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SeguridadYAccesoBtn7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeguridadYAccesoBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguridadYAccesoBtn7ActionPerformed(evt);
            }
        });
        jPanel1.add(SeguridadYAccesoBtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 550, 70, 20));

        SeguridadYAccesoBtn8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        SeguridadYAccesoBtn8.setForeground(new java.awt.Color(204, 204, 204));
        SeguridadYAccesoBtn8.setText("Medio");
        SeguridadYAccesoBtn8.setToolTipText("");
        SeguridadYAccesoBtn8.setBorder(null);
        SeguridadYAccesoBtn8.setBorderPainted(false);
        SeguridadYAccesoBtn8.setContentAreaFilled(false);
        SeguridadYAccesoBtn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SeguridadYAccesoBtn8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeguridadYAccesoBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguridadYAccesoBtn8ActionPerformed(evt);
            }
        });
        jPanel1.add(SeguridadYAccesoBtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 550, 70, 20));

        IdUsuario.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        IdUsuario.setForeground(new java.awt.Color(106, 30, 85));
        IdUsuario.setText("@Usuario1");
        jPanel1.add(IdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 1000, -1, -1));

        NombreUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        NombreUsuario.setForeground(new java.awt.Color(204, 204, 204));
        NombreUsuario.setText("Usuario Ejemplo");
        jPanel1.add(NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 980, -1, -1));

        jButton1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("...");
        jButton1.setAlignmentY(0.0F);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 460, 50, 40));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("🔍Buscar");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, 270, -1));

        jLabel39.setFont(new java.awt.Font("Roboto Black", 1, 22)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(204, 204, 204));
        jLabel39.setText("Usuario");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 170, 30));

        CuentaBtn8.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        CuentaBtn8.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn8.setText("0");
        CuentaBtn8.setBorder(null);
        CuentaBtn8.setBorderPainted(false);
        CuentaBtn8.setContentAreaFilled(false);
        CuentaBtn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn8ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 80, 50));

        CuentaBtn9.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        CuentaBtn9.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn9.setText("Siguientes");
        CuentaBtn9.setBorder(null);
        CuentaBtn9.setBorderPainted(false);
        CuentaBtn9.setContentAreaFilled(false);
        CuentaBtn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn9ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, 80, 50));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("Seguir");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 230, -1, -1));

        CuentaBtn10.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        CuentaBtn10.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn10.setText("''''''''");
        CuentaBtn10.setBorder(null);
        CuentaBtn10.setBorderPainted(false);
        CuentaBtn10.setContentAreaFilled(false);
        CuentaBtn10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn10ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 110, 80, 50));

        CuentaBtn11.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        CuentaBtn11.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn11.setText("''''''''");
        CuentaBtn11.setBorder(null);
        CuentaBtn11.setBorderPainted(false);
        CuentaBtn11.setContentAreaFilled(false);
        CuentaBtn11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn11ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 110, 80, 50));

        CuentaBtn12.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        CuentaBtn12.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn12.setText("''''''''");
        CuentaBtn12.setBorder(null);
        CuentaBtn12.setBorderPainted(false);
        CuentaBtn12.setContentAreaFilled(false);
        CuentaBtn12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn12ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 110, 80, 50));

        CuentaBtn13.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        CuentaBtn13.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn13.setText("''''''''");
        CuentaBtn13.setBorder(null);
        CuentaBtn13.setBorderPainted(false);
        CuentaBtn13.setContentAreaFilled(false);
        CuentaBtn13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn13ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 110, 80, 50));

        CuentaBtn14.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        CuentaBtn14.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn14.setText("00000");
        CuentaBtn14.setBorder(null);
        CuentaBtn14.setBorderPainted(false);
        CuentaBtn14.setContentAreaFilled(false);
        CuentaBtn14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn14ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 120, 80, 50));

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setText("Seguir");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 130, -1, -1));

        CuentaBtn15.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        CuentaBtn15.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn15.setText("''''''''");
        CuentaBtn15.setBorder(null);
        CuentaBtn15.setBorderPainted(false);
        CuentaBtn15.setContentAreaFilled(false);
        CuentaBtn15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn15ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 160, 80, 50));

        CuentaBtn16.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        CuentaBtn16.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn16.setText("00000");
        CuentaBtn16.setBorder(null);
        CuentaBtn16.setBorderPainted(false);
        CuentaBtn16.setContentAreaFilled(false);
        CuentaBtn16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn16ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 170, 80, 50));

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setText("Seguir");
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 180, -1, -1));

        CuentaBtn17.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        CuentaBtn17.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn17.setText("''''''''");
        CuentaBtn17.setBorder(null);
        CuentaBtn17.setBorderPainted(false);
        CuentaBtn17.setContentAreaFilled(false);
        CuentaBtn17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn17ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 210, 80, 50));

        jSeparator5.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator5.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 10, 1040));

        jSeparator6.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator6.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 80, 80, 220));

        jSeparator7.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator7.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 80, 20, 220));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 300, 280, 20));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 80, 280, 10));

        CuentaBtn2.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        CuentaBtn2.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn2.setText("Seguidores");
        CuentaBtn2.setBorder(null);
        CuentaBtn2.setBorderPainted(false);
        CuentaBtn2.setContentAreaFilled(false);
        CuentaBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 80, 50));

        jLabel40.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(204, 204, 204));
        jLabel40.setText("Te puede interesar");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 80, 210, 30));

        jButton4.setBackground(new java.awt.Color(106, 30, 85));
        jButton4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(106, 30, 85));
        jButton4.setText("...");
        jButton4.setAlignmentY(0.0F);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 980, 50, 40));

        CuentaBtn6.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        CuentaBtn6.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn6.setText("Tendencia");
        CuentaBtn6.setBorder(null);
        CuentaBtn6.setBorderPainted(false);
        CuentaBtn6.setContentAreaFilled(false);
        CuentaBtn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn6ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 440, 80, 50));

        CuentaBtn18.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        CuentaBtn18.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn18.setText("#0000");
        CuentaBtn18.setBorder(null);
        CuentaBtn18.setBorderPainted(false);
        CuentaBtn18.setContentAreaFilled(false);
        CuentaBtn18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn18ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn18, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 460, 80, 50));

        CuentaBtn19.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        CuentaBtn19.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn19.setText("Mostrar mas");
        CuentaBtn19.setBorder(null);
        CuentaBtn19.setBorderPainted(false);
        CuentaBtn19.setContentAreaFilled(false);
        CuentaBtn19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn19ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn19, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 510, 80, 50));

        CuentaBtn3.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        CuentaBtn3.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn3.setText("Tendencia");
        CuentaBtn3.setBorder(null);
        CuentaBtn3.setBorderPainted(false);
        CuentaBtn3.setContentAreaFilled(false);
        CuentaBtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn3ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 370, 80, 50));

        CuentaBtn20.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        CuentaBtn20.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn20.setText("Tendencia");
        CuentaBtn20.setBorder(null);
        CuentaBtn20.setBorderPainted(false);
        CuentaBtn20.setContentAreaFilled(false);
        CuentaBtn20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn20ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn20, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 370, 80, 50));

        CuentaBtn21.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        CuentaBtn21.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn21.setText("1000 publicaciones");
        CuentaBtn21.setBorder(null);
        CuentaBtn21.setBorderPainted(false);
        CuentaBtn21.setContentAreaFilled(false);
        CuentaBtn21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn21ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn21, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 410, 100, 50));

        CuentaBtn22.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        CuentaBtn22.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn22.setText("0000");
        CuentaBtn22.setBorder(null);
        CuentaBtn22.setBorderPainted(false);
        CuentaBtn22.setContentAreaFilled(false);
        CuentaBtn22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn22ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn22, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 390, 80, 50));

        CuentaBtn23.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        CuentaBtn23.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn23.setText("1000 publicaciones");
        CuentaBtn23.setBorder(null);
        CuentaBtn23.setBorderPainted(false);
        CuentaBtn23.setContentAreaFilled(false);
        CuentaBtn23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn23ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn23, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 410, 100, 50));

        jButton8.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("...");
        jButton8.setAlignmentY(0.0F);
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 380, 50, 40));

        CuentaBtn24.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        CuentaBtn24.setForeground(new java.awt.Color(204, 204, 204));
        CuentaBtn24.setText("Mostrar mas");
        CuentaBtn24.setBorder(null);
        CuentaBtn24.setBorderPainted(false);
        CuentaBtn24.setContentAreaFilled(false);
        CuentaBtn24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuentaBtn24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CuentaBtn24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBtn24ActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaBtn24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 260, 80, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1562, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1054, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1042, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InicioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InicioBtnActionPerformed

    private void ComunidadesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComunidadesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComunidadesBtnActionPerformed

    private void NotificacionesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotificacionesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NotificacionesBtnActionPerformed

    private void GuardadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardadoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardadoBtnActionPerformed

    private void PerfilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerfilBtnActionPerformed

    private void PostearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostearBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PostearBtnActionPerformed

    private void CuentaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtnActionPerformed
        JPanelGeneraPanel.setSelectedIndex(0);
    }//GEN-LAST:event_CuentaBtnActionPerformed

    private void SeguridadYAccesoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguridadYAccesoBtnActionPerformed
        JPanelGeneraPanel.setSelectedIndex(9);
    }//GEN-LAST:event_SeguridadYAccesoBtnActionPerformed

    private void ExplorarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExplorarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExplorarBtnActionPerformed

    private void PerfilBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerfilBtn1ActionPerformed

    private void PerfilBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerfilBtn2ActionPerformed

    private void PerfilBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerfilBtn3ActionPerformed

    private void PerfilBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerfilBtn4ActionPerformed

    private void SeguridadYAccesoBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguridadYAccesoBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeguridadYAccesoBtn2ActionPerformed

    private void CuentaBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn1ActionPerformed

    private void CuentaBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn4ActionPerformed

    private void CuentaBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn5ActionPerformed

    private void CuentaBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn7ActionPerformed

    private void SeguridadYAccesoBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguridadYAccesoBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeguridadYAccesoBtn3ActionPerformed

    private void SeguridadYAccesoBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguridadYAccesoBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeguridadYAccesoBtn4ActionPerformed

    private void SeguridadYAccesoBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguridadYAccesoBtn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeguridadYAccesoBtn5ActionPerformed

    private void SeguridadYAccesoBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguridadYAccesoBtn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeguridadYAccesoBtn6ActionPerformed

    private void SeguridadYAccesoBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguridadYAccesoBtn7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeguridadYAccesoBtn7ActionPerformed

    private void SeguridadYAccesoBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguridadYAccesoBtn8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeguridadYAccesoBtn8ActionPerformed

    private void CuentaBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn8ActionPerformed

    private void CuentaBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn9ActionPerformed

    private void CuentaBtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn10ActionPerformed

    private void CuentaBtn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn11ActionPerformed

    private void CuentaBtn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn12ActionPerformed

    private void CuentaBtn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn13ActionPerformed

    private void CuentaBtn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn14ActionPerformed

    private void CuentaBtn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn15ActionPerformed

    private void CuentaBtn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn16ActionPerformed

    private void CuentaBtn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn17ActionPerformed

    private void CuentaBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn2ActionPerformed

    private void CuentaBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn6ActionPerformed

    private void CuentaBtn18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn18ActionPerformed

    private void CuentaBtn19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn19ActionPerformed

    private void CuentaBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn3ActionPerformed

    private void CuentaBtn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn20ActionPerformed

    private void CuentaBtn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn21ActionPerformed

    private void CuentaBtn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn22ActionPerformed

    private void CuentaBtn23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn23ActionPerformed

    private void CuentaBtn24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBtn24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBtn24ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ComunidadesBtn;
    private javax.swing.JButton CuentaBtn;
    private javax.swing.JButton CuentaBtn1;
    private javax.swing.JButton CuentaBtn10;
    private javax.swing.JButton CuentaBtn11;
    private javax.swing.JButton CuentaBtn12;
    private javax.swing.JButton CuentaBtn13;
    private javax.swing.JButton CuentaBtn14;
    private javax.swing.JButton CuentaBtn15;
    private javax.swing.JButton CuentaBtn16;
    private javax.swing.JButton CuentaBtn17;
    private javax.swing.JButton CuentaBtn18;
    private javax.swing.JButton CuentaBtn19;
    private javax.swing.JButton CuentaBtn2;
    private javax.swing.JButton CuentaBtn20;
    private javax.swing.JButton CuentaBtn21;
    private javax.swing.JButton CuentaBtn22;
    private javax.swing.JButton CuentaBtn23;
    private javax.swing.JButton CuentaBtn24;
    private javax.swing.JButton CuentaBtn3;
    private javax.swing.JButton CuentaBtn4;
    private javax.swing.JButton CuentaBtn5;
    private javax.swing.JButton CuentaBtn6;
    private javax.swing.JButton CuentaBtn7;
    private javax.swing.JButton CuentaBtn8;
    private javax.swing.JButton CuentaBtn9;
    private javax.swing.JButton ExplorarBtn;
    private javax.swing.JButton GuardadoBtn;
    private javax.swing.JLabel IdUsuario;
    private javax.swing.JButton InicioBtn;
    private javax.swing.JLabel NombreUsuario;
    private javax.swing.JButton NotificacionesBtn;
    private javax.swing.JButton PerfilBtn;
    private javax.swing.JButton PerfilBtn1;
    private javax.swing.JButton PerfilBtn2;
    private javax.swing.JButton PerfilBtn3;
    private javax.swing.JButton PerfilBtn4;
    private javax.swing.JPanel PerfilPanel;
    private javax.swing.JLabel Perfil_Img;
    private javax.swing.JButton PostearBtn;
    private javax.swing.JButton SeguridadYAccesoBtn;
    private javax.swing.JButton SeguridadYAccesoBtn2;
    private javax.swing.JButton SeguridadYAccesoBtn3;
    private javax.swing.JButton SeguridadYAccesoBtn4;
    private javax.swing.JButton SeguridadYAccesoBtn5;
    private javax.swing.JButton SeguridadYAccesoBtn6;
    private javax.swing.JButton SeguridadYAccesoBtn7;
    private javax.swing.JButton SeguridadYAccesoBtn8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
